// Final check on 30e9252: rubric rows (appended to out/audit.jsonl, then copied to reaudit/results.jsonl).
import { row } from '../audit/rec.mjs';
const S = '(run-3-check, on disk)';
row('C-08', { roles: 'requester (CONFIGURE window on the uncontrolled Pipeline batch-upstream), approver-1, manager (revoke), auditor (records), admin (monitor)',
  V: "✓ admin's Manage Jenkins monitor lists batch-upstream as changed under a permission window, with a Mark as reviewed button, during and after the window",
  G: "✓ with the D-50a global default (Run as Specific User auditor, no Configure; the warning is gone) the requester's Pipeline properties([authorizationMatrix(... requester Job/Configure, Job/Read ...)]) ran as E2E Auditor (#14 SUCCESS) and the job kept <properties/>; after the window was revoked the requester's configure is 403, and his Build Now (#16) is reverted the same way",
  R: "✓ the build log names the reverted entries: \"[Batch Control] This build widened the authorization of 'batch-upstream' (USER:requester hudson.model.Item.Configure, USER:requester hudson.model.Item.Read, inheritance changed to InheritGlobalStrategy), which is guarded because of a permission window; the change was undone. Ask an administrator.\"",
  C: "✓ GRANT_VIOLATION by auditor with the grant id, for #14 (20260930-211319-m52g3k) and for the after-window #16 (20260930-211420-oc0o7v)",
  E: `✓ C-08-3-global-default-auditor, C-08-10-build-log-reverted, C-08-11-grant-violation-record, C-08-12-monitor-lists-item, C-08-14-after-window-build-log, C-08-15-monitor-after-window ${S}`,
  note: 'DEF-38 fixed by D-58a/b. Global default removed and batch-upstream restored afterwards', defect: '' });
row('DEF-38', { roles: 'see C-08', V: 'n.a.', G: '✓ the self-grant through a Pipeline properties step under a non-Configure build account is reverted during and after the window (C-08)', R: 'n.a.', C: '✓ GRANT_VIOLATION per reverted save', E: `✓ C-08-10, C-08-14 ${S}`, note: 'fixed (D-58, D-58a, D-58b)' });
row('C-08a', { roles: 'admin (monitor), requester (build), auditor (records)',
  V: "✓ the monitor lists batch-upstream and its replayed run #15 with Mark as reviewed (only for admin). Its first paragraph still says \"Until an administrator or a user with Configure permission saves them, changes that widen their authorization are undone\", the ordinary-save rule D-58b replaced (DEF-39)",
  G: "✓ Mark as reviewed clears the item (the monitor block disappears); a later widening is kept: the same Pipeline script's build #17 wrote the requester's entries and they stayed (the risk LIMITATIONS 35 describes)",
  R: 'n.a.', C: "✓ GUARD_REVIEWED by admin: \"Marked as reviewed by 'admin': 1 changed-under-a-permission-window entry at or below this item cleared.\"; no GRANT_VIOLATION for #17",
  E: `✓ C-08-17-monitor-mark-reviewed(-after), C-08-18-guard-reviewed-record, C-08-19-after-review-build-log ${S}`, verdict: 'PASS (partial)', defect: 'DEF-39 (new, text)' });
row('C-08b', { roles: 'configurer (native Item/Configure + BatchControl/Request), requester (window 2 and 3), manager (revoke)',
  V: "✓ the job's Batch Control page shows the configurer \"This job was changed under a temporary permission window and has not been reviewed ... Check what was changed ... and the Pipeline script first\", the replayed runs #18 and #15, and Mark as reviewed; the requester (no native Configure) gets no button",
  G: "✓ before the review the configurer's matrix edit (approver-2 Job/Read) is undone; after Mark as reviewed the same edit is kept (InheritParentStrategy + approver-2 Job/Read)",
  R: "✗ the 403 page for the native Configure holder says the entries \"would give lasting permissions to a user who holds or recently held a temporary permission window, for example you, if your Configure permission on it comes only from such a window ... Ask an administrator\": it describes the replaced principal rule, does not fit a native Configure holder, and does not say that the job must be marked as reviewed, which he may do himself (DEF-39)",
  C: "✓ GRANT_VIOLATION by configurer (USER:approver-2 hudson.model.Item.Read) before; GUARD_REVIEWED by configurer after (20260930-212228-wo5mnc, 20260930-212317-2ssrw1)",
  E: `✓ C-08-21-native-before(-matrix), C-08-22-job-page-review-section, C-08-23-job-page-after-review, C-08-21-native-after(-matrix) ${S}`, defect: 'DEF-39 (new)' });
row('C-08c', { roles: 'requester (window holder, then Build only), configurer (native Configure), admin',
  V: '✓ Replay offered to the window holder on #14; both review surfaces list the marked runs (#15, then #18)',
  G: "✓ the requester's Replay (edited script) ran as #15 and is marked; re-runs of #15 by requester (Pipeline Rebuild), configurer (Replay, before and after the review) and of the admin's #18 by requester are refused, no build (next number unchanged); admin's Replay of #15 is allowed (#18) and #18 is marked in turn",
  R: "✓ Pipeline Rebuild and Replay: 400 page \"Build #15 of 'batch-upstream' cannot be re-run: this run's script was replayed under a temporary permission window. Ask an administrator.\" · the rebuild plugin's Rebuild on #15 answers only with the toast \"Failed.\", and neither the build page nor the job page says why (DEF-41)",
  C: "✗ REPLAY_UNDER_GRANT for #15 names requester and the grant (✓), but the one for the admin's #18 reads \"by 'admin' whose permission came only from a permission window\", which is false; the refused re-runs are recorded as TRIGGER_BLOCKED \"switch=approvalRequired\" on a job that does not require approval (DEF-40)",
  E: `✓ C-08-13-replay-under-grant-record, C-08-16-rerun-refused-configurer, C-08-16-rerun-refused-requester-pipeline-rebuild, C-08-16-rerun-requester-link0, C-08-20-replay-refused-after-review, C-08-24-rerun-of-admin-rerun-refused ${S}`, defect: 'DEF-40 (new), DEF-41 (new)' });
