// Re-check on 9fabbf3: rubric rows for C-08a..c and DEF-39..41.
import { row } from '../audit/rec.mjs';
const S = '(run-3-recheck, on disk)';
row('C-08a', { roles: 'admin (monitor), requester (build), auditor (records)',
  V: "✓ the monitor now reads \"Until one of them is marked as reviewed (below, or by a user with Configure permission and Batch Control/Request on the job's Batch Control page), changes that widen its authorization are undone, whoever saves it. Saving the item does not end this.\" and lists batch-upstream with its marked runs and Mark as reviewed",
  G: '✓ Mark as reviewed clears the item; the next build of the same script (#22) writes its entries without a revert (no log line, no GRANT_VIOLATION, CONFIGURE by auditor)',
  R: 'n.a.', C: "✓ GUARD_REVIEWED 20260930-225815-12xbc4 by admin",
  E: `✓ C-08-12-monitor-lists-item, C-08-17-monitor-mark-reviewed(-after), C-08-18-guard-reviewed-record, C-08-19-after-review-build-log ${S}`, note: 'DEF-39 (1) fixed' });
row('C-08b', { roles: 'configurer (native Item/Configure + BatchControl/Request), requester (window 5), manager (revoke)',
  V: '✓ job page review section with the marked runs #21, #20, #18, #15 and Mark as reviewed; none for the requester',
  G: '✓ the matrix edit (approver-2 Job/Read) is undone before the review and kept after it',
  R: "✓ 403 \"Authorization entries not kept\": \"The item is guarded because it is covered by a temporary permission window, or was changed under one and has not been reviewed. Changes that widen its authorization are undone, whoever saves it, until someone uses Mark as reviewed. Your other changes were saved. An administrator can use Mark as reviewed on the Batch Control monitor under Manage Jenkins. A user with Configure permission on it and Batch Control/Request can use it on its Batch Control page [link]. While a permission window still covers it, ask an administrator.\"",
  C: '✓ GRANT_VIOLATION by configurer before; GUARD_REVIEWED 20260930-225920-5ip0bv by configurer after',
  E: `✓ C-08-21-native-before(-matrix), C-08-22-job-page-review-section, C-08-23-job-page-after-review, C-08-21-native-after ${S}`, note: 'DEF-39 (2) fixed' });
row('C-08c', { roles: 'requester (window holder, then Build only), configurer (native Configure), admin',
  V: "✓ on the marked #20 the requester sees only Pipeline's own Rebuild (/replay, LIMITATIONS 41: cannot be hidden), not the rebuild plugin's Rebuild, which he still sees on the unmarked #19; the configurer sees Replay; admin sees both; the job page shows no Rebuild Last to anyone",
  G: "✓ #20 (requester's Replay under window 4) marked; requester's Pipeline Rebuild, configurer's Replay (before and after the review), a forced POST to the hidden rebuild-plugin URL and the requester's re-run of the admin's #21 are all refused, no build; admin's Replay of #20 allowed (#21) and marked",
  R: "✓ every refusal is the 400 page \"Build #20 of 'batch-upstream' cannot be re-run: this run's script was replayed under a temporary permission window. Ask an administrator.\"",
  C: "✓ refusals: TRIGGER_BLOCKED \"cause=REPLAY switch=replayedUnderGrant: Blocked a re-run of job 'batch-upstream' build #20 by 'configurer' ...\"; admin: REPLAY_UNDER_GRANT \"Run #21 was started by 'admin' as a re-run of run #20, whose script was replayed under a permission window; it carries the same mark ...\". unresolvedSource not reachable from the browser (a missing source build is a 404 before the plugin sees it)",
  E: `✓ C-08-13-replay-under-grant-record, C-08-16-rerun-refused-requester, C-08-16-rerun-refused-configurer, C-08-20-replay-refused-after-review, C-08-24-rerun-of-admin-rerun-refused, DEF-41-requester-marked-sidebar, DEF-41-requester-unmarked-sidebar ${S}`, note: 'DEF-40, DEF-41 fixed' });
row('DEF-39', { roles: 'see C-08a, C-08b', V: 'n.a.', G: '✓ monitor and 403 name Mark as reviewed and where it is (monitor under Manage Jenkins; the job\'s Batch Control page, linked)', R: '✓ (C-08b)', C: 'n.a.', E: `✓ C-08-12, C-08-21-native-before ${S}`, note: 'fixed' });
row('DEF-40', { roles: 'see C-08c', V: 'n.a.', G: '✓ refusals carry switch=replayedUnderGrant; the admin re-run record names the marked source run #20 and no longer claims a window permission', R: 'n.a.', C: '✓', E: `✓ changes.csv rows quoted; C-08-13 ${S}`, note: 'fixed; unresolvedSource not observed (not reachable in the browser)' });
row('DEF-41', { roles: 'see C-08c', V: "✓ the rebuild plugin's Rebuild is hidden from a non-admin on a marked run (shown on unmarked runs); no Rebuild Last on the job page", G: '✓ the forced POST to the hidden URL is refused with the plain 400 message', R: '✓', C: '✓ TRIGGER_BLOCKED switch=replayedUnderGrant', E: `✓ DEF-41-requester-marked-sidebar, DEF-41-requester-unmarked-sidebar ${S}`, note: 'fixed' });
