package io.jenkins.plugins.batchcontrol.action;

import com.cloudbees.hudson.plugins.folder.computed.ComputedFolder;
import edu.umd.cs.findbugs.annotations.CheckForNull;
import hudson.model.Action;
import hudson.model.Item;
import io.jenkins.plugins.batchcontrol.model.ActivationRequest;
import io.jenkins.plugins.batchcontrol.policy.ActivationService;
import io.jenkins.plugins.batchcontrol.security.BatchControlPermissions;
import io.jenkins.plugins.batchcontrol.ui.ActivationView;
import io.jenkins.plugins.batchcontrol.ui.SectionAccess;
import io.jenkins.plugins.batchcontrol.ui.Visibility;
import java.util.ArrayList;
import java.util.List;
import jenkins.model.Jenkins;
import org.kohsuke.accmod.Restricted;
import org.kohsuke.accmod.restrictions.NoExternalUse;

/**
 * Activation on a computed folder (multibranch project, organization folder), which carries the
 * activation of the jobs it generates (D-46c, SPEC item 6a).
 *
 * <ul>
 *   <li>{@code summary.jelly} shows the folder's state (activated / not activated / on hold) on
 *       the folder page to {@code Item/Read} holders while run control is on, with a link to the
 *       request form for a {@code BatchControl/Request} holder.</li>
 *   <li>{@code <folder>/batch-control/activation} is the request form ({@link JobActivationForm}).
 *       Without {@code BatchControl/Request} {@link #getUrlName()} is {@code null}, so the whole
 *       {@code <folder>/batch-control/} space answers 404 (SPEC item 2, as on a job).</li>
 * </ul>
 *
 * <p>No sidebar entry; the action never changes state itself.
 */
@Restricted(NoExternalUse.class)
public class ComputedFolderActivationAction implements Action {

    private final ComputedFolder<?> folder;

    public ComputedFolderActivationAction(ComputedFolder<?> folder) {
        this.folder = folder;
    }

    public ComputedFolder<?> getFolder() {
        return folder;
    }

    @Override
    @CheckForNull
    public String getIconFileName() {
        return null;
    }

    @Override
    public String getDisplayName() {
        return "Activation";
    }

    /** {@code null} without {@code BatchControl/Request}: the URL space is absent (404). */
    @Override
    @CheckForNull
    public String getUrlName() {
        return isCanRequest() ? "batch-control" : null;
    }

    /** Stapler: serves {@code <folder>/batch-control/activation}; the submission re-checks. */
    public JobActivationForm getActivation() {
        return new JobActivationForm(folder);
    }

    // ---------------------------------------------------------------- summary (Jelly)

    /** Run control on and the viewer holds {@code Item/Read} on the folder. */
    public boolean isShown() {
        return folder.hasPermission(Item.READ) && JobActivationNoticeAction.isRunControlEnabled();
    }

    public boolean isCanRequest() {
        return Jenkins.get().hasPermission(BatchControlPermissions.REQUEST);
    }

    public boolean isActivated() {
        return ActivationView.isActivated(folder);
    }

    public boolean isHeld() {
        return ActivationView.isHeld(folder);
    }

    /**
     * A computed folder generated by another computed folder (a repository project of an
     * organization folder) is carried by that folder (D-46c,
     * {@link ActivationService#activationSubject}); the summary then names it. {@code null}
     * otherwise.
     */
    @CheckForNull
    public Item getCarrier() {
        return ActivationView.carrierOf(folder);
    }

    public String carrierState(Item carrier) {
        return ActivationView.stateLabel(carrier);
    }

    @CheckForNull
    public String carrierUrl(Item carrier) {
        return carrier.hasPermission(Item.READ) ? carrier.getUrl() : null;
    }

    /** The PENDING requests of this folder the viewer may see (P-09). */
    public List<ActivationRequest> getPendingRequests() {
        List<ActivationRequest> visible = new ArrayList<>();
        if (!new SectionAccess().isActivations()) {
            return visible;
        }
        for (ActivationRequest request : ActivationService.get().listPendingForJob(folder.getFullName())) {
            if (Visibility.canSeeActivationRequest(request)) {
                visible.add(request);
            }
        }
        return visible;
    }

    public String actionLabel(ActivationRequest.Action action) {
        return ActivationView.actionLabel(action);
    }
}
