import { login, close, BASE, api, requestRun, sleep } from '../lib.mjs';
import { row, ev } from '../audit/rec.mjs';
import { formPost } from '../audit/restsubmit.mjs';
const T = String(Date.now()).slice(-4); const J = `c23-${T}`;
const ad = await login('admin');
await ad.page.goto(`${BASE}/view/all/newJob`); await ad.page.fill('#name', J); await ad.page.locator('label:has-text("Freestyle project")').first().click();
await Promise.all([ad.page.waitForNavigation(), ad.page.locator('#ok-button').click()]); await ad.page.waitForTimeout(1200);
await ad.page.locator('textarea[name="_.jobApproversText"]').first().fill('approver-2');
await Promise.all([ad.page.waitForNavigation(), ad.page.locator('button[name="Submit"]').click()]);
const { page } = await login('requester');
const url = await requestRun(page, `/job/${J}/`, { reason: `Verify C-23 ${T}`, approvers: [] });
const id = url.match(/(\d{8}-\d{6}-\w+)/)[1];
// ARRANGE: the job stops inheriting global grants; only admin keeps an entry (requester loses Item/Read)
const x = (await api('admin', `/job/${J}/config.xml`, { raw: true })).text;
const prop = `<hudson.security.AuthorizationMatrixProperty><inheritanceStrategy class="org.jenkinsci.plugins.matrixauth.inheritance.NonInheritingStrategy"/><permission>USER:hudson.model.Item.Read:admin</permission></hudson.security.AuthorizationMatrixProperty>`;
const y = x.replace('<properties>', `<properties>${prop}`);
const put = await api('admin', `/job/${J}/config.xml`, { method: 'POST', body: y, headers: { 'Content-Type': 'application/xml' } });
const read = (await api('requester', `/job/${J}/api/json`)).status;
const c1 = await formPost('requester', `/batch-control/requests/${id}/changeApprover`, { approvers: 'approver-1' });
const c2 = await formPost('requester', `/batch-control/requests/${id}/changeApprover`, { approvers: 'admin' });
const d = await api('admin', `/batch-control/requests/${id}/`); const appr = (d.text.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').match(/Approvers (\S+)/) || [])[1];
ev(`C-23 put ${put.status}; requester job ${read}; changeApprover approver-1 ${JSON.stringify(c1)}; admin ${JSON.stringify(c2)}; approvers now ${appr}`);
row('C-23', { roles: 'requester (lost Item/Read on the job), admin (arrange)', V: 'n.a.', G: `${read === 404 && c1.status >= 400 && c2.status >= 400 && appr === 'approver-2' ? '✓' : '✗'} after the job stopped inheriting (requester /job/${J}/ ${read}) the requester's changeApprover to approver-1 -> ${c1.status}, to admin -> ${c2.status}; the request keeps approvers ${appr} (job list approver-2)`, R: `✓ "${(c1.msg || '').slice(0, 120)}"`, C: 'n.a.', E: '✓ text', note: 'the non-inheriting job matrix was arranged by an admin config.xml POST' });
await close();
