import { chromium } from 'playwright';
import { password } from '../lib.mjs';
const BASE = 'http://localhost:8081';
const b = await chromium.launch({ channel: 'chrome' }); const page = await (await b.newContext()).newPage();
await page.goto(`${BASE}/login`); await page.fill('#j_username', 'admin'); await page.fill('input[name="j_password"]', password('admin'));
await Promise.all([page.waitForLoadState('load'), page.click('button[name="Submit"], button[type="submit"]')]);
await page.goto(`${BASE}/job/batch-unstable/`);
console.log((await page.locator('#side-panel a').allInnerTexts()).map((t) => t.trim()).filter(Boolean).slice(0, 12));
console.log((await page.locator('#main-panel').innerText()).replace(/\s+/g, ' ').slice(0, 300));
await b.close();
