import { login, close, shot, api, BASE } from '../lib.mjs';
import { row, ev, mainText } from '../audit/rec.mjs';
const id = (await api('admin', '/batch-control/history/requests.csv')).text.split('\n').slice(1).find((l) => /,approver-1,(PENDING|EXECUTED|REJECTED)/.test(l)).split(',')[0];
const { page } = await login('approver-unlisted');
const st = (await page.goto(`${BASE}/batch-control/requests/${id}/`)).status(); const forms = await page.locator('form[name="approve"]').count();
const s = await shot(page, '#main-panel table', 'B2-07-approver-unlisted-detail', { pad: 8 });
ev(`DOCS B2-07 ${id} ${st} forms ${forms}`);
const R = (i, g, c = '', d = '') => row(i, { roles: 'reader of README.md / docs/LIMITATIONS.md at d2d59f9', V: 'n.a.', G: g, R: 'n.a.', C: c || 'n.a.', E: '✓ text (README/LIMITATIONS lines quoted)', defect: d });
row('B2-07', { roles: 'approver-unlisted (Approve + Job/Read)', V: `✓ opens a request designated to approver-1 (${st}) without a decision form (${forms})`, G: '✓ matches LIMITATIONS 21/22 as rewritten: an Approve holder who is not designated sees a request only through Item/Read on the job (DD-07 fixed)', R: 'n.a.', C: 'n.a.', E: s ? '✓ B2-07-approver-unlisted-detail' : '✗' });
R('DD-07', '✓ LIMITATIONS 22 now says it is not an exception to item 21: a non-designated Approve holder sees the request only through Item/Read, as anyone would; behaviour matches (B2-07)');
R('DD-08', '✓ LIMITATIONS 23: "A grant request\'s approver set can be changed while it is pending, from the Change Approvers action" - matches B3-12');
R('DD-09', '✓ LIMITATIONS 9 and README step 2: Manage Roles / Assign Roles saves keep the variant (role-strategy 918); the monitor stays as a safety net - matches B8-R1/B8-R2');
R('DD-10', '✓ README Roadmap: "The global configuration and the authorization strategy variants already round-trip through JCasC"');
R('DD-11', '✓ README Requirements: "cloudbees-folder and ionicons-api, both required"');
R('DD-12', '✓ README step 1 table has Notify before expiry, Send e-mail notifications and the Batch Control strategy entry; the labels "Grant duration options (minutes, comma-separated)" and "Results that open an incident (comma-separated)" are the screen labels');
R('DD-13', '✓ e2e/README.md "Re-audit driver": init.groovy.d runs on the first boot only, seed fixes do not reach existing items');
R('DD-04', '✓ README step 2: "There is no such button on the Security page"; Install on the /manage monitor, Revert under System > Batch Control - matches A-21');
R('B8-06', '✓ README no longer claims a migration button on the Authorization page (DD-04 fixed)');
R('B19-04', '✓ README Roadmap no longer says JCasC is not in this release (DD-10 fixed)');
R('B21-01', '✓ Requirements name ionicons-api (DD-11 fixed); a matrix-type strategy is still needed, as README says');
row('B21-03', { roles: 'reader of README.md, manager', V: 'n.a.', G: '✗ step 1 labels and fields match the screen (DD-12 fixed), step 2 names the real controls (DD-04 fixed), step 4 describes activation (DD-03 fixed); but step 1 says "Manage Jenkins → System → Batch Control, which needs BatchControl/Manage" while a BatchControl/Manage holder gets 403 there and has to use the Configuration entry on the Batch Control page (/batch-control-configuration/, B1-22), which README does not mention (DD-14)', R: 'n.a.', C: 'n.a.', E: '✓ README.md line 183; B1-22-manager-config', defect: 'DD-14 (new)' });
R('B21-04', '✓ "Dashboard (titled Run Dashboard on the page itself)" (DD-05 fixed); Activations and the job-page activation notice are described (DD-03 fixed)');
R('DD-14', '✗ README step 1: "Manage Jenkins → System → Batch Control, which needs BatchControl/Manage" - a BatchControl/Manage holder (manager) gets 403 on Manage Jenkins → System; the section he can use is Batch Control → Configuration (/batch-control-configuration/), not mentioned in README', '', 'DD-14 (new)');
await close();
