// DD-14 / DD-15 / B21-03 on the final build: where a BatchControl/Manage holder configures; LIMITATIONS 33 rename text.
import { login, close, shot, BASE } from '../lib.mjs';
import { row, ev, sidebar } from '../audit/rec.mjs';
const m = await login('manager');
await m.page.goto(`${BASE}/batch-control/`);
const sb = await sidebar(m.page);
const s1 = await shot(m.page, m.page.locator('#side-panel a').filter({ hasText: 'Configuration' }).first(), 'DD-14-1-manager-sidebar', { pad: 12 });
const st = (await m.page.goto(`${BASE}/batch-control-configuration/`)).status();
const mj = (await m.page.goto(`${BASE}/manage/`)).status();
await m.context.close();
const a = await login('admin');
await a.page.goto(`${BASE}/manage/`);
const entry = a.page.locator('#main-panel a', { hasText: /^Batch Control$/ }).first();
const has = await entry.count(); const href = has ? await entry.getAttribute('href') : null;
const s2 = has ? await shot(a.page, entry, 'DD-14-2-manage-jenkins-entry', { pad: 12 }) : null;
await a.context.close();
ev(`F5 manager sidebar ${sb}; /batch-control-configuration/ ${st}; /manage ${mj}; admin Manage Jenkins entry ${has} ${href}`);
const ok = sb.includes('Configuration') && st === 200 && has;
row('DD-14', { roles: 'manager (BatchControl/Manage), admin, reader of README.md', V: `${ok ? '✓' : '✗'} manager: "Configuration" in the Batch Control sidebar, page ${st} (Manage Jenkins ${mj}); admin: "Batch Control" on Manage Jenkins (${href})`, G: '✓ README step 1 now opens with "Holding BatchControl/Manage without Overall/Administer? Open /batch-control-configuration/, or Batch Control → Configuration. Manage Jenkins is not open to you." and describes both places', R: 'n.a.', C: 'n.a.', E: s1 && s2 ? '✓ DD-14-1-manager-sidebar, DD-14-2-manage-jenkins-entry (run-3-final)' : '✗' });
row('B21-03', { roles: 'reader of README.md, manager', V: 'n.a.', G: `${ok ? '✓' : '✗'} step 1 names Batch Control → Configuration for BatchControl/Manage holders (DD-14 fixed); the other points as in the re-verification (DD-12, DD-04, DD-03 fixed)`, R: 'n.a.', C: 'n.a.', E: '✓ README.md step 1; DD-14-1' });
row('DD-15', { roles: 'reader of LIMITATIONS.md', V: 'n.a.', G: '✓ LIMITATIONS 33 now says: "A CONFIGURE window also lets its holder rename the job, to any free name in its folder, because Jenkins allows a rename to anyone who may configure the job ... An approver who wants to rule out renames has no narrower window to grant", and that a CREATE restriction governs its own renames - matches C-15 and B7-19', R: 'n.a.', C: 'n.a.', E: '✓ text' });
await close();
