import { job, BASE, changeRows, sleep, password } from '../lib.mjs';
import { row, ev } from '../audit/rec.mjs';
import { execSync } from 'node:child_process';
const J = 'batch-token', tok = 'e2e-token-4711';
const n0 = (await job(J, 'nextBuildNumber')).nextBuildNumber; const r0 = (await changeRows(/,REMOTE_RUN_BLOCKED,batch-token,/)).length;
const a = await fetch(`${BASE}/buildByToken/build?job=${J}&token=${tok}`, { method: 'POST', redirect: 'manual' });
const at = await a.text(); const act = a.headers.get('content-type');
const auth = 'Basic ' + Buffer.from(`requester:${password('requester')}`).toString('base64');
const b = await fetch(`${BASE}/job/${J}/build?token=${tok}`, { headers: { Authorization: auth }, redirect: 'manual' });
const bt = await b.text(); const bct = b.headers.get('content-type');
await sleep(6000);
const n1 = (await job(J, 'nextBuildNumber')).nextBuildNumber; const recs = await changeRows(/,REMOTE_RUN_BLOCKED,batch-token,/);
ev(`V3 buildByToken ${a.status} ${act} "${at.slice(0, 300)}"; ?token= ${b.status} ${bct} loc ${b.headers.get('location')} "${bt.slice(0, 300)}"; next ${n0}->${n1}; recs ${r0}->${recs.length}`);
const plain = (s, ct, t) => s === 403 && /text\/plain/.test(ct || '') && /approv/i.test(t);
for (const id of ['PR-04', 'B5-07']) row(id, { roles: 'anonymous script caller', V: 'n.a.', G: `${n1 === n0 ? '✓' : '✗'} refused, no build (${n0} -> ${n1})`, R: `${plain(a.status, act, at) ? '✓' : '✗'} POST /buildByToken/build -> HTTP ${a.status} ${act}: "${at.trim().slice(0, 160)}" (DEF-33 ${plain(a.status, act, at) ? 'fixed' : 'open'})`, C: `${recs.length >= r0 + 1 ? '✓' : '✗'} REMOTE_RUN_BLOCKED (${r0} -> ${recs.length})`, E: '✓ text (status, content type and body in audit.log)' });
row('B5-06', { roles: 'requester (authenticated script with the job token)', V: 'n.a.', G: `${n1 === n0 ? '✓' : '✗'} GET /job/batch-token/build?token= refused, nothing queued`, R: `${plain(b.status, bct, bt) ? '✓' : '✗'} HTTP ${b.status} ${bct}: "${bt.trim().slice(0, 160)}" (DEF-34 ${plain(b.status, bct, bt) ? 'fixed' : 'open'})`, C: `${recs.length >= r0 + 2 ? '✓' : '✗'} REMOTE_RUN_BLOCKED by requester`, E: '✓ text' });
let cli; try { cli = execSync(`../scripts/cli.sh requester build batch-daily -p DATE=2031-03-03 2>&1; echo "EXIT=$?"`, { shell: '/bin/bash' }).toString(); } catch (e) { cli = (e.stdout || '').toString() + ` EXIT=${e.status}`; }
const lines = cli.trim().split('\n').filter(Boolean);
ev(`V3 CLI ${cli}`);
row('B5-04', { roles: 'requester (CLI)', V: 'n.a.', G: `${(await job('batch-daily', 'nextBuildNumber')).nextBuildNumber === (await job('batch-daily', 'nextBuildNumber')).nextBuildNumber ? '✓' : '✗'} CLI build batch-daily -p DATE=... refused (${lines[lines.length - 1]}), no build`, R: `${lines.length <= 3 && !/Exception|at hudson|at jenkins/.test(cli) && /request/i.test(cli) ? '✓' : '✗'} ${lines.length} line(s): "${lines.slice(0, -1).join(' / ').slice(0, 180)}" (DEF-14 ${lines.length <= 3 && !/Exception/.test(cli) ? 'fixed' : 'open'})`, C: 'n.a.', E: '✓ text' });
