package io.jenkins.plugins.batchcontrol.listener;

import com.cloudbees.hudson.plugins.folder.computed.ComputedFolder;
import hudson.Extension;
import hudson.XmlFile;
import hudson.model.Item;
import hudson.model.Saveable;
import hudson.model.listeners.SaveableListener;
import io.jenkins.plugins.batchcontrol.model.ChangeRecord;
import io.jenkins.plugins.batchcontrol.model.ChangeType;
import io.jenkins.plugins.batchcontrol.model.GrantAction;
import io.jenkins.plugins.batchcontrol.store.FileStore;
import io.jenkins.plugins.batchcontrol.store.SecretMasker;
import io.jenkins.plugins.batchcontrol.store.Store;
import io.jenkins.plugins.batchcontrol.store.UnifiedDiff;
import java.io.IOException;
import java.util.concurrent.locks.ReentrantLock;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.kohsuke.accmod.Restricted;
import org.kohsuke.accmod.restrictions.NoExternalUse;

/**
 * Records CONFIGURE changes with a unified diff (SPEC item 9) and maintains the per-item config
 * snapshots ({@code snapshots/<encoded fullName>.xml}, latest only — ARCHITECTURE section 5).
 *
 * <p>{@link SaveableListener} is the one hook every config-writing path goes through — UI form
 * submit ({@code save()}), REST {@code config.xml} POST and CLI {@code update-job}
 * ({@code updateByXml}), Job DSL, and programmatic saves — so nothing escapes the record
 * (SPEC item 9: "regardless of the path").
 *
 * <p>Both diff sides are masked with {@link SecretMasker} BEFORE diffing, so no hunk can ever
 * carry a secret. When only secret payloads changed (both sides mask to the same text), a
 * masked-change note is stored instead of an empty diff.
 *
 * <p>Both sides are compared and diffed in their {@link ConfigNormalizer normalised} form, so a
 * save that changes no user-editable configuration (an unchanged job saved after a plugin
 * upgrade, a computed folder saving itself during indexing) writes no record, no patch and no new
 * snapshot (SPEC item 9, #20). The snapshot keeps the raw file, which other readers parse.
 *
 * <p>Items whose parent is a {@link ComputedFolder} (branch jobs, the projects of an organization
 * folder) are skipped: their configuration is generated by indexing and cannot be edited by a
 * user. Their runs are still recorded (D-32).
 *
 * <p>The read → diff → snapshot swap of one item runs under that item's lock stripe, so rapid
 * consecutive saves chain baseline-consistently (each diff is previous-config vs new-config,
 * T-RT-20) while saves of unrelated items do not wait for each other.
 */
@Extension
@Restricted(NoExternalUse.class)
public class ConfigSnapshotListener extends SaveableListener {

    private static final Logger LOGGER = Logger.getLogger(ConfigSnapshotListener.class.getName());

    private static final int STRIPES = 64;

    /** Serializes snapshot read → diff → snapshot write per item so records never lose a revision. */
    private static final ReentrantLock[] LOCKS = new ReentrantLock[STRIPES];

    static {
        for (int i = 0; i < STRIPES; i++) {
            LOCKS[i] = new ReentrantLock();
        }
    }

    @Override
    public void onChange(Saveable o, XmlFile file) {
        if (!(o instanceof Item)) {
            return;
        }
        if (ChangeRecording.isSuppressed() || !ChangeRecording.isActive()) {
            return;
        }
        Item item = (Item) o;
        if (item.getParent() instanceof ComputedFolder) {
            return; // generated by indexing, not user-editable (#20); runs are still recorded (D-32)
        }
        String fullName = item.getFullName();
        ReentrantLock lock = LOCKS[Math.floorMod(fullName.hashCode(), STRIPES)];
        lock.lock();
        try {
            String newXml;
            try {
                newXml = file.asString();
            } catch (IOException e) {
                LOGGER.log(Level.WARNING, "Cannot read saved config of '" + fullName + "'", e);
                return;
            }
            Store store = FileStore.get();
            String oldXml = store.loadConfigSnapshot(fullName);
            if (oldXml == null) {
                // First sighting: the creation-time initial save (the CREATE record comes from
                // the ItemListener) or an item predating the switch. Establish the baseline.
                store.saveConfigSnapshot(fullName, newXml);
                return;
            }
            if (oldXml.equals(newXml)) {
                return; // no-op save, nothing changed
            }
            String normalizedOld = ConfigNormalizer.normalize(oldXml);
            String normalizedNew = ConfigNormalizer.normalize(newXml);
            if (normalizedOld.equals(normalizedNew)) {
                // Only plugin versions or persisted actions differ: no user-editable change, and the
                // snapshot is left as it is (it still compares equal next time).
                return;
            }
            // Mask BOTH sides before diffing so no hunk can ever carry a secret.
            String maskedOld = SecretMasker.mask(normalizedOld);
            String maskedNew = SecretMasker.mask(normalizedNew);
            String diff;
            if (maskedOld.equals(maskedNew)) {
                diff = "Only secret values changed; secrets are stored as "
                        + SecretMasker.MASK + " and never in plaintext.";
            } else {
                diff = UnifiedDiff.diff(maskedOld, maskedNew);
            }
            String user = ChangeRecording.currentUser();
            ChangeRecord record = ChangeRecord.create(ChangeType.CONFIGURE, fullName, user, null);
            record.setDiff(diff);
            record.setGrantId(ChangeRecording.activeGrantIdFor(user, fullName, GrantAction.CONFIGURE));
            store.saveConfigSnapshot(fullName, newXml);
            store.appendChangeRecord(record);
        } finally {
            lock.unlock();
        }
    }
}
