"""Which request answers 403 on the configuration page for a BatchControl/Manage-only user; where the page is linked from."""
from lib import Session, close, api
s = Session("manager")
s.go("/manage/batch-control-configuration/")
s.page.wait_for_timeout(1500)
print("bad:", s.bad)
s.go("/batch-control/")
print("overview links to config:", [a.get_attribute("href") for a in s.page.locator("a[href*='configuration']").all()])
print("/manage/ for manager:", api("manager", "/manage/").status_code)
s.done()
s = Session("admin"); s.go("/manage/")
print("admin /manage/ config links:", [a.get_attribute("href") for a in s.page.locator("a[href*='batch-control']").all()][:5])
s.go("/batch-control/")
print("admin overview config links:", [a.get_attribute("href") for a in s.page.locator("#main-panel a[href*='configur']").all()])
s.done(); close()
