// e2e-05 EX repro: requester's change-approvers form submitted after the request was decided in another session.
import { login, BASE, shot, text, log, close } from './lib.mjs';
const { page, context } = await login('requester');
await page.goto(`${BASE}/job/fresh-daily/batch-control/`);
await page.fill('textarea[name="reason"]', 'e2e-05 X1b stale change approvers');
for (const ap of ['approver-1', 'approver-2']) await page.locator(`input[name="approvers"][value="${ap}"]`).check({ force: true });
await Promise.all([page.waitForLoadState('load'), page.click('button[name="Submit"]')]);
const R = page.url().match(/requests\/([^/]+)/)[1];
const ap = await login('approver-1');
await ap.page.goto(`${BASE}/batch-control/requests/${R}/`);
await ap.page.fill('form[action$="/reject"] textarea[name="comment"]', 'rejected while the requester edits');
await Promise.all([ap.page.waitForLoadState('load'), ap.page.locator('form[action$="/reject"] button').click()]);
const ch = page.locator('form[action$="/changeApprover"]');
await ch.locator('input[name="approvers"][value="approver-2"]').setChecked(false, { force: true });
await Promise.all([page.waitForLoadState('load'), ch.locator('button[name="Submit"]').click()]);
const errs = await page.$$eval('#main-panel .error, #main-panel .jenkins-alert, #main-panel .validation-error-area', (es) => es.map((e) => e.innerText.trim()).filter(Boolean));
const hasForm = await page.locator('form[action$="/changeApprover"]').count();
log('X1b', R, 'url', page.url().replace(BASE, ''), '| messages', errs, '| change-approver form still shown:', hasForm, '|', (await text(page)).replace(/\s+/g, ' ').slice(0, 400));
await shot(page, ['#main-panel .jenkins-alert', 'form[action$="/changeApprover"]'], 'X1b-01-stale-change-approvers-full');
await close();
