// FD-05/FD-06 neighbour: approved, then the job is disabled before it starts (quiet period 90 s).
import { login, BASE, shot, text, api, log, close, sleep } from '../lib.mjs';
const flat = (s) => s.replace(/\s+/g, ' ');
const r = await login('requester');
await r.page.goto(`${BASE}/job/fresh-token/batch-control/`);
await r.page.fill('textarea[name="reason"]', 'verify: approved, then disabled in the quiet period');
await r.page.locator('input[name="approvers"][value="approver-1"]').check({ force: true });
await Promise.all([r.page.waitForLoadState('load'), r.page.click('button[name="Submit"]')]);
const id = r.page.url().match(/requests\/([^/]+)/)[1];
await r.context.close();
const a = await login('approver-1');
await a.page.goto(`${BASE}/batch-control/requests/${id}/`);
await Promise.all([a.page.waitForLoadState('load'), a.page.locator('form[action$="/approve"] button').first().click()]);
log('approved', id, flat(await text(a.page)).slice(0, 250));
log('queue', (await api('admin', '/queue/api/json?tree=items%5Btask%5Bname%5D,why%5D')).body);
log('disable', (await api('admin', '/job/fresh-token/disable', { method: 'POST' })).status);
await sleep(3000);
await a.page.reload();
log('after disable', flat(await text(a.page)).slice(0, 700));
await shot(a.page, '#main-panel', 'FD05-approved-then-disabled');
log('queue', (await api('admin', '/queue/api/json?tree=items%5Btask%5Bname%5D,why%5D')).body);
await a.context.close();
console.log(id);
await close();
