package io.jenkins.plugins.batchcontrol;

import hudson.ExtensionList;
import hudson.model.FreeStyleBuild;
import hudson.model.FreeStyleProject;
import hudson.model.Result;
import hudson.model.queue.QueueTaskFuture;
import io.jenkins.plugins.batchcontrol.config.BatchControlGlobalConfiguration;
import io.jenkins.plugins.batchcontrol.config.BatchControlJobProperty;
import io.jenkins.plugins.batchcontrol.model.ChangeRecord;
import io.jenkins.plugins.batchcontrol.model.ChangeType;
import io.jenkins.plugins.batchcontrol.model.Incident;
import io.jenkins.plugins.batchcontrol.ops.IncidentService;
import io.jenkins.plugins.batchcontrol.ops.RetentionPeriodicWork;
import io.jenkins.plugins.batchcontrol.store.BatchClock;
import io.jenkins.plugins.batchcontrol.store.FileStore;
import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Clock;
import java.time.Instant;
import java.time.YearMonth;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;
import org.htmlunit.HttpMethod;
import org.htmlunit.WebRequest;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.jvnet.hudson.test.FailureBuilder;
import org.jvnet.hudson.test.JenkinsRule;
import org.jvnet.hudson.test.junit.jupiter.WithJenkins;

import static io.jenkins.plugins.batchcontrol.BatchControlFixtures.setBatchControl;
import static io.jenkins.plugins.batchcontrol.BatchControlFixtures.uncontrolled;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * SPEC item 4, "retention deletes in bounded batches and never holds the store lock that the
 * queue gate or build completion waits on for longer than one batch; the queue gate performs no
 * store I/O that can wait behind bulk work. Scheduling never stalls because retention is
 * running" (#18). Matrix row T-04-12 (note 68).
 *
 * <p>An expired month is made large enough that deleting it takes seconds: 12,000 change records
 * each with a diff file and 12,000 incidents each with an XML file, generated by copying one real
 * record of each kind (so every generated file is exactly what the store writes). While the
 * retention work is observed deleting (some generated files gone, others not yet), an unapproved
 * manual run of an approval-required job is attempted (the gate refuses and audits it) and an
 * uncontrolled job is scheduled. Both must be answered, the build must start and its run record
 * must be written, before the retention work returns. An implementation that holds the store lock
 * across the whole deletion makes the gate (which runs under the queue lock) and the build's
 * completion record wait for the end of the deletion, and fails every one of those orderings.
 *
 * Written from docs/SPEC.md, docs/ARCHITECTURE.md section 5, issue #18 and docs/TEST-MATRIX.md
 * only (no src/main knowledge).
 */
@WithJenkins
public class RetentionConcurrencyTest {

    private static final int COPIES = 12_000;
    private static final long WAIT_SECONDS = 60;

    private JenkinsRule j;
    private final ExecutorService pool = Executors.newFixedThreadPool(3);

    @BeforeEach
    public void setUp(JenkinsRule rule) throws Exception {
        this.j = rule;
        BatchControlGlobalConfiguration cfg = BatchControlGlobalConfiguration.get();
        cfg.setRunControlEnabled(true);
        cfg.setApprovers(Arrays.asList("a1"));
        cfg.setRetentionMonths(1);
        cfg.save();
    }

    @AfterEach
    public void tearDown() throws Exception {
        pool.shutdownNow();
        BatchClock.reset();
    }

    /**
     * T-04-12 (#18): while retention deletes a large expired month, a gated (refused) submission
     * is answered, an uncontrolled build starts, and that build's run record is written, all
     * before the retention work returns; the refused job still has no build.
     */
    @Test
    public void t_04_12_schedulingAndCompletionDoNotWaitForRetention() throws Exception {
        FreeStyleProject gated = setBatchControlled(j.createFreeStyleProject("gated-x"));
        FreeStyleProject free = uncontrolled(j.createFreeStyleProject("free-y"));

        // Warm-up outside the measurement: the first refused POST (page rendering, Stapler) and
        // the first build of a fresh instance are slow for reasons unrelated to the store.
        assertTrue(refuseBuild(gated) >= 400, "fixture: the gated job refuses an unapproved run");
        j.buildAndAssertSuccess(free);
        j.waitUntilNoActivity();

        YearMonth oldMonth = YearMonth.now(ZoneOffset.UTC).minusMonths(3);
        List<Path> sample = generateExpiredMonth(oldMonth);

        AtomicLong retentionDone = new AtomicLong(Long.MAX_VALUE);
        Future<?> retention = pool.submit(() -> {
            try {
                ExtensionList.lookupSingleton(RetentionPeriodicWork.class).doRun();
            } finally {
                retentionDone.set(System.nanoTime());
            }
            return null;
        });

        // wait until the deletion is observably under way, but not finished
        long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(WAIT_SECONDS);
        while (sample.stream().allMatch(Files::exists)) {
            assertTrue(System.nanoTime() < deadline, "fixture: retention never started deleting the expired month");
            Thread.sleep(5); // polling an observable condition, not waiting out a timeout
        }
        long gone = sample.stream().filter(p -> !Files.exists(p)).count();
        assertTrue(gone < sample.size() && retentionDone.get() == Long.MAX_VALUE, "fixture: the submissions must happen while the deletion is still running ("
                + gone + " of " + sample.size() + " sampled files gone); enlarge COPIES if this fails");

        int gatedNext = gated.getNextBuildNumber();
        long submittedAt = System.nanoTime();
        Future<Integer> refused = pool.submit(() -> refuseBuild(gated));
        Future<QueueTaskFuture<FreeStyleBuild>> scheduled = pool.submit(() -> free.scheduleBuild2(0));

        int refusedStatus = refused.get(WAIT_SECONDS, TimeUnit.SECONDS);
        long refusedAt = System.nanoTime();
        QueueTaskFuture<FreeStyleBuild> queued = scheduled.get(WAIT_SECONDS, TimeUnit.SECONDS);
        assertNotNull(queued, "an uncontrolled job must be accepted by the queue");
        queued.getStartCondition().get(WAIT_SECONDS, TimeUnit.SECONDS);
        long startedAt = System.nanoTime();
        FreeStyleBuild build = queued.get(WAIT_SECONDS, TimeUnit.SECONDS);
        assertEquals(Result.SUCCESS, build.getResult());

        String runId = build.getParent().getFullName() + "#" + build.getNumber();
        long recordedAt = 0;
        while (recordedAt == 0) {
            assertTrue(System.nanoTime() < deadline + TimeUnit.SECONDS.toNanos(WAIT_SECONDS), "the build's run record was never written");
            if (FileStore.get().listRunRecords(YearMonth.now(BatchClock.clock())).stream()
                    .anyMatch(rec -> runId.equals(rec.getRunId()))) {
                recordedAt = System.nanoTime();
            } else {
                Thread.sleep(5); // polling an observable condition, not waiting out a timeout
            }
        }

        retention.get(WAIT_SECONDS * 4, TimeUnit.SECONDS);
        long done = retentionDone.get();
        String timing = " (after submission: refusal " + ms(refusedAt - submittedAt) + " ms, build start "
                + ms(startedAt - submittedAt) + " ms, run record " + ms(recordedAt - submittedAt)
                + " ms, retention returned " + ms(done - submittedAt) + " ms)";
        System.out.println("[retention-vs-queue]" + timing);
        assertTrue(refusedAt < done, "the gate's refusal must be answered while retention runs, not after it (#18)" + timing);
        assertTrue(startedAt < done, "an uncontrolled build must start while retention runs; scheduling stalled behind the"
                + " deletion (#18)" + timing);
        assertTrue(recordedAt < done, "the build's completion record must not wait for the whole deletion (#18)" + timing);

        // the refused run stays refused (standard blocking triple)
        assertTrue(refusedStatus >= 400, "the unapproved manual run must be refused, was HTTP " + refusedStatus);
        assertTrue(j.jenkins.getQueue().isEmpty(), "the queue must be empty");
        assertEquals(gatedNext, gated.getNextBuildNumber(), "the gated job's next build number must be unchanged");
        j.waitUntilNoActivity();
        assertTrue(gated.getBuilds().isEmpty(), "the gated job must have no build");

        // premise: retention really deleted the month it was working on
        assertTrue(FileStore.get().listRunRecords(oldMonth).isEmpty(), "fixture: the expired month's runs are deleted");
        assertTrue(FileStore.get().listChangeRecords(oldMonth).isEmpty(), "fixture: the expired month's changes are deleted");
        assertTrue(IncidentService.get().list(oldMonth).isEmpty(), "fixture: the expired month's incidents are deleted");
    }

    // ---------------------------------------------------------------------------------------

    /** An unapproved manual POST /build; returns the HTTP status. */
    private int refuseBuild(FreeStyleProject target) throws Exception {
        JenkinsRule.WebClient wc = j.createWebClient().withThrowExceptionOnFailingStatusCode(false);
        wc.getOptions().setJavaScriptEnabled(false); // measure the gate, not HtmlUnit's page scripts
        wc.getOptions().setCssEnabled(false);
        return wc.getPage(new WebRequest(wc.createCrumbedUrl(target.getUrl() + "build"), HttpMethod.POST))
                .getWebResponse().getStatusCode();
    }

    private static long ms(long nanos) {
        return nanos / 1_000_000;
    }

    private static FreeStyleProject setBatchControlled(FreeStyleProject job) throws Exception {
        setBatchControl(job, new BatchControlJobProperty(true));
        return job;
    }

    /**
     * Makes {@code month} hold one real CONFIGURE record with its diff and one real incident, then
     * {@link #COPIES} copies of each under fresh ids. Returns a sample of generated files spread
     * over both kinds.
     */
    private List<Path> generateExpiredMonth(YearMonth month) throws Exception {
        Instant at = month.atDay(15).atTime(12, 0).toInstant(ZoneOffset.UTC);
        BatchClock.setForTest(Clock.fixed(at, ZoneOffset.UTC));
        FreeStyleProject diffJob = uncontrolled(j.createFreeStyleProject("tpl-diff"));
        diffJob.setDescription("template-change");
        FreeStyleProject failJob = uncontrolled(j.createFreeStyleProject("tpl-fail"));
        failJob.getBuildersList().add(new FailureBuilder());
        j.assertBuildStatus(Result.FAILURE, failJob.scheduleBuild2(0));
        j.waitUntilNoActivity();

        List<ChangeRecord> configures = FileStore.get().listChangeRecords(month).stream()
                .filter(rec -> rec.getType() == ChangeType.CONFIGURE && "tpl-diff".equals(rec.getTarget()))
                .filter(rec -> rec.getDiff() != null && rec.getDiff().contains("template-change"))
                .collect(Collectors.toList());
        assertEquals(1, configures.size(), "fixture: one CONFIGURE record with the template diff in " + month);
        List<Incident> incidents = IncidentService.get().list(month);
        assertEquals(1, incidents.size(), "fixture: one incident in " + month);
        BatchClock.reset();

        Path store = StoreDataFixtures.storeDir();
        String bucket = StoreDataFixtures.monthName(month);
        List<Path> sample = new ArrayList<>();
        sample.addAll(copy(configures.get(0).getId(), store.resolve("changes/" + bucket + ".jsonl"),
                store.resolve("changes/diff"), ".patch", at));
        sample.addAll(copy(incidents.get(0).getId(), store.resolve("incidents/index/" + bucket + ".jsonl"),
                store.resolve("incidents"), ".xml", at.plusSeconds(1)));
        return sample;
    }

    /** Copies the month-file line and the per-record file of {@code id} {@link #COPIES} times. */
    private static List<Path> copy(String id, Path monthFile, Path dir, String suffix, Instant at)
            throws Exception {
        assertTrue(id.matches("[0-9]{8}-[0-9]{6}-[A-Za-z0-9]{6}"), "fixture: documented id form: " + id);
        Path recordFile = dir.resolve(id + suffix);
        assertTrue(Files.exists(recordFile), "fixture: " + recordFile + " is stored");
        List<String> lines = Files.readAllLines(monthFile, StandardCharsets.UTF_8).stream()
                .filter(l -> l.contains(id)).collect(Collectors.toList());
        assertEquals(1, lines.size(), "fixture: " + monthFile + " holds the record's line");
        String line = lines.get(0);
        String body = Files.readString(recordFile, StandardCharsets.UTF_8);
        String prefix = id.substring(0, 15);
        List<Path> sample = new ArrayList<>();
        try (BufferedWriter out = Files.newBufferedWriter(monthFile, StandardCharsets.UTF_8,
                StandardOpenOption.APPEND)) {
            for (int i = 0; i < COPIES; i++) {
                String copyId = prefix + "-" + String.format(Locale.ROOT, "%06d", i);
                out.write(line.replace(id, copyId));
                out.write('\n');
                Path file = dir.resolve(copyId + suffix);
                Files.writeString(file, body.replace(id, copyId), StandardCharsets.UTF_8);
                if (i % 200 == 0) {
                    sample.add(file);
                }
            }
        }
        assertFalse(sample.isEmpty());
        return sample;
    }
}
