package io.jenkins.plugins.batchcontrol;

import io.jenkins.plugins.batchcontrol.model.CauseType;
import io.jenkins.plugins.batchcontrol.model.RunRecord;
import io.jenkins.plugins.batchcontrol.store.FileStore;
import java.io.BufferedWriter;
import java.io.IOException;
import java.lang.management.ManagementFactory;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Instant;
import java.time.YearMonth;
import java.util.List;
import java.util.Locale;
import jenkins.model.Jenkins;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Bulk data for the storage-volume rows (matrix notes 64-67). Records are generated by writing
 * the store's month files directly in the JSONL format of ARCHITECTURE section 5 (one record per
 * line in {@code runs/YYYY-MM.jsonl}), because appending 150,000 records through the store would
 * make the rows minutes long.
 *
 * <p>The exact field layout of a line is not documented, so it is never guessed: one sentinel
 * record is appended through the public store API, the line the store wrote for it is read back,
 * and that line becomes the template. Every generated line is therefore exactly what the store
 * itself writes, with only the sentinel values substituted.
 */
final class StoreDataFixtures {

    private static final String SENTINEL_RUN_ID = "tplrunidq7x";
    private static final String SENTINEL_JOB = "tpljobq7x";
    private static final int SENTINEL_NUMBER = 424242;
    /** A month no row uses, so the sentinel's file can be removed again. */
    private static final Instant SENTINEL_AT = Instant.parse("2001-01-15T12:00:00Z");

    private StoreDataFixtures() {
    }

    static Path storeDir() {
        return Jenkins.get().getRootDir().toPath().resolve("batch-control");
    }

    /** The ASCII month bucket name ARCHITECTURE section 5 documents ({@code YYYY-MM}). */
    static String monthName(YearMonth month) {
        return String.format(Locale.ROOT, "%04d-%02d", month.getYear(), month.getMonthValue());
    }

    static Path runsFile(YearMonth month) {
        return storeDir().resolve("runs").resolve(monthName(month) + ".jsonl");
    }

    /** A run-record line template taken from what the store itself writes. */
    static final class RunLine {
        private final String template;
        private final boolean isoTime;

        private RunLine(String template, boolean isoTime) {
            this.template = template;
            this.isoTime = isoTime;
        }

        String render(String runId, String job, int number, Instant startedAt) {
            return template
                    .replace(SENTINEL_RUN_ID, runId)
                    .replace(SENTINEL_JOB, job)
                    .replace(String.valueOf(SENTINEL_NUMBER), String.valueOf(number))
                    .replace(isoTime ? SENTINEL_AT.toString() : String.valueOf(SENTINEL_AT.toEpochMilli()),
                            isoTime ? startedAt.toString() : String.valueOf(startedAt.toEpochMilli()));
        }
    }

    static RunLine runLineTemplate() throws IOException {
        FileStore.get().appendRunRecord(new RunRecord(SENTINEL_RUN_ID, SENTINEL_JOB, SENTINEL_NUMBER,
                CauseType.USER, "SUCCESS", SENTINEL_AT, 777L));
        YearMonth month = YearMonth.of(2001, 1);
        Path file = runsFile(month);
        assertTrue(Files.isRegularFile(file), "fixture: the store must write run records to " + file);
        List<String> lines = Files.readAllLines(file, StandardCharsets.UTF_8);
        assertEquals(1, lines.size(), "fixture: exactly the sentinel line in " + file);
        String line = lines.get(0);
        assertTrue(line.contains(SENTINEL_RUN_ID) && line.contains(SENTINEL_JOB)
                && line.contains(String.valueOf(SENTINEL_NUMBER)), "fixture: the sentinel values must appear in the stored line: " + line);
        boolean iso = line.contains(SENTINEL_AT.toString());
        assertTrue(iso || line.contains(String.valueOf(SENTINEL_AT.toEpochMilli())), "fixture: the start time must appear in the stored line: " + line);
        Files.delete(file);
        return new RunLine(line, iso);
    }

    /**
     * Writes {@code count} run records into {@code month}'s file, evenly spaced from {@code from}
     * (inclusive) to {@code to} (exclusive), oldest first (append order), over {@code jobs} jobs
     * named {@code jobPrefix + k}.
     */
    static void writeRunMonth(RunLine line, YearMonth month, int count, Instant from, Instant to,
            String jobPrefix, int jobs) throws IOException {
        Path file = runsFile(month);
        Files.createDirectories(file.getParent());
        long span = to.toEpochMilli() - from.toEpochMilli();
        try (BufferedWriter out = Files.newBufferedWriter(file, StandardCharsets.UTF_8,
                StandardOpenOption.CREATE, StandardOpenOption.APPEND)) {
            for (int i = 0; i < count; i++) {
                Instant at = Instant.ofEpochMilli(from.toEpochMilli() + span * i / count);
                String job = jobPrefix + (i % jobs);
                out.write(line.render(job + "#" + (i + 1), job, i + 1, at));
                out.write('\n');
            }
        }
    }

    static long lineCount(Path file) throws IOException {
        try (var lines = Files.lines(file, StandardCharsets.UTF_8)) {
            return lines.count();
        }
    }

    /** Bytes allocated on the heap by all threads so far (HotSpot's ThreadMXBean extension). */
    static long allocatedBytes() {
        com.sun.management.ThreadMXBean bean =
                (com.sun.management.ThreadMXBean) ManagementFactory.getThreadMXBean();
        assertTrue(bean.isThreadAllocatedMemorySupported() && bean.isThreadAllocatedMemoryEnabled(), "fixture: the JVM must report allocated bytes");
        return bean.getTotalThreadAllocatedBytes();
    }
}
