// A-04 re-enable of the dismissed monitor through System > Administrative monitors, then JCasC reload (undo group entry).
import { login, close, shot, BASE, api } from '../lib.mjs';
import { row, ev } from './rec.mjs';
const { page } = await login('admin');
await page.goto(`${BASE}/manage/configure`);
const sec = page.locator('.jenkins-section:has(label:has-text("Batch Control: standing change"))').first();
await sec.locator('button:has-text("Administrative monitors")').click(); await page.waitForTimeout(800);
const lbl = page.locator('label:has-text("Batch Control: standing change permissions bypass change control")').first();
const lbl2 = page.locator('label:has-text("Batch Control: grants need a Batch Control authorization strategy")').first();
const input = page.locator('input[json="io.jenkins.plugins.batchcontrol.ops.ConfigureWithoutGrantMonitor"]').first();
const off = !(await input.isChecked());
const s2 = await shot(page, [lbl, lbl2], 'A-04-2-administrative-monitors-list', { pad: 8 });
if (off) await lbl.click();
await Promise.all([page.waitForNavigation({ waitUntil: 'load' }), page.locator('button[name="Submit"]').click()]);
await page.goto(`${BASE}/manage/`);
const backOn = await page.locator('[data-monitor-id="io.jenkins.plugins.batchcontrol.ops.ConfigureWithoutGrantMonitor"]').count();
const rl = await api('admin', '/manage/configuration-as-code/reload', { method: 'POST' });
ev(`A-04 unticked after dismiss ${off}; re-ticked -> shown ${backOn}; JCasC reload ${rl.status}`);
const m = await login('manager'); const mr = (await m.page.goto(`${BASE}/manage/`)).status();
row('A-04', { roles: 'admin, manager', V: `✓ admin only (manager /manage ${mr})`, G: `${off && backOn ? '✓' : '✗'} rendered by l:adminMonitor (div.app-adminmonitor.jenkins-alert-warning, "Review authorization strategy" + Dismiss ×, the standard controls); Dismiss hid it from /manage and unticked "Batch Control: standing change permissions bypass change control" under System > Administrative monitors (${off}); ticking it + Save brings it back (${backOn}). Both Batch Control monitors are listed there`, R: 'n.a.', C: 'n.a.', E: s2 ? '✓ A-03-2-standing-monitor-user-and-group, A-04-2-administrative-monitors-list' : '✗', note: 'header popup not captured (no badge found in this header layout); Dismiss disables the monitor until re-ticked (U-09)' });
row('A-03', { roles: 'admin, manager', V: `✓ admin only (manager /manage ${mr})`, G: '✗ user variant ✓ (DEF-07 fixed: "User configurer(E2E Standing Configurer): Job/Configure, Job/Delete", no "not a Batch Control strategy" clause); group variant (authenticated given Job/Configure on the Security page): the monitor lists "Group authenticated: Job/Configure" and ALSO "User approver-1 ... User requester: Job/Configure" for all ten accounts, none of which has a Configure entry, under the heading "the users and groups below hold ... directly from the authorization strategy", so user vs group is still confused on screen (DEF-29). No getAllSids/deprecation line in any log', R: 'n.a.', C: 'n.a.', E: '✓ A-03-1-standing-monitor-user, A-03-2a-security-group-authenticated-configure, A-03-2-standing-monitor-user-and-group', defect: 'DEF-29', note: 'group entry removed again by JCasC reload' });
await close();
