// A-16 (+B3-04, B3-05) and A-15 (+B15-01, B15-03, B15-04, B15-08): two approvers, first decision wins, mails.
import { login, close, shot, BASE, api, job, waitFor, requestRun, sleep } from '../lib.mjs';
import { row, ev, mainText } from './rec.mjs';
import { findMail, mailText, mailShot, followAsRecipient } from './mail.mjs';
const before = (await job('batch-daily')).nextBuildNumber;
const rq = await login('requester');
const tag = Date.now();
const url = await requestRun(rq.page, '/job/batch-daily/', { reason: `Audit A-16 ${tag}: re-run the 30th partial load.\nLink: http://evil.example/ (must stay quoted)`, approvers: ['approver-1', 'approver-2'], params: { DATE: '2026-09-30', MODE: 'partial' } });
const id = url.match(/(\d{8}-\d{6}-\w+)/)[1];
const d0 = await mainText(rq.page);
const s1 = await shot(rq.page, '#main-panel table', 'A-16-1-request-both-approvers', { pad: 10 });
// mails to both approvers
const m1 = await findMail(`to:approver-1@e2e.local ${id}`); const m2 = await findMail(`to:approver-2@e2e.local ${id}`);
const t1 = m1 ? await mailText(m1) : '';
const sm = m1 ? await mailShot(m1, 'A-15-1-mail-request-created') : null;
const link1 = (t1.match(/https?:\/\/\S+/) || [])[0];
const f1 = link1 ? await followAsRecipient(link1, 'approver-2') : null;
// approver-2 decides
const a2 = await login('approver-2');
await a2.page.goto(url);
const s2 = await shot(a2.page, ['#main-panel table', 'form[name="approve"]'], 'A-16-2-approver-2-decision-screen', { pad: 8 });
await a2.page.fill('form[name="approve"] textarea[name="comment"]', 'Go ahead (approver-2).');
await Promise.all([a2.page.waitForLoadState('load'), a2.page.locator('form[name="approve"] button').first().click()]);
const notice = await mainText(a2.page);
const built = await waitFor(async () => { const j = await job('batch-daily', 'nextBuildNumber,lastBuild[number,building]'); return j.nextBuildNumber > before && !j.lastBuild.building ? j : null; }, { timeout: 90000 });
await sleep(10000);
const j2 = await job('batch-daily', 'nextBuildNumber,lastBuild[number,result,actions[parameters[name,value],causes[shortDescription]]]');
const params = (j2.lastBuild.actions.find((x) => x.parameters) || {}).parameters;
const causes = (j2.lastBuild.actions.find((x) => x.causes) || {}).causes;
const a1 = await login('approver-1');
await a1.page.goto(url);
const forms = await a1.page.locator('form[name="approve"], form[name="reject"]').count();
const v1 = await mainText(a1.page);
const s3 = await shot(a1.page, '#main-panel table', 'A-16-3-approver-1-closed', { pad: 8 });
const csv = (await api('admin', '/batch-control/history/requests.csv')).text.split('\n').find((l) => l.startsWith(id)) || '';
const mr = await findMail(`to:requester@e2e.local subject:approved ${id}`);
const tr = mr ? await mailText(mr) : '';
const smr = mr ? await mailShot(mr, 'A-15-2-mail-approved') : null;
const linkr = (tr.match(/https?:\/\/\S+/) || [])[0];
const fr = linkr ? await followAsRecipient(linkr, 'requester') : null;
ev(`A-16 ${id} detail "${d0.slice(0, 200)}"; mails a1 ${!!m1} a2 ${!!m2}; link ${link1} -> ${JSON.stringify(f1)}; notice "${notice.slice(0, 200)}"; builds +${j2.nextBuildNumber - before} #${j2.lastBuild.number} ${j2.lastBuild.result} ${JSON.stringify(params)} ${JSON.stringify(causes)}; a1 forms ${forms} "${v1.slice(0, 250)}"; csv ${csv}; approved mail ${!!mr} link ${linkr} -> ${JSON.stringify(fr)}`);
ev(`A-15 created mail text:\n${t1}`);
// reject path + REJECTED mail
const url2 = await requestRun(rq.page, '/job/batch-pipeline/', { reason: `Audit A-15 ${tag}: reject path`, approvers: ['approver-1'] });
const id2 = url2.match(/(\d{8}-\d{6}-\w+)/)[1];
await a1.page.goto(url2);
await a1.page.fill('form[name="reject"] textarea[name="comment"]', 'Not today: vendor fix missing.');
await Promise.all([a1.page.waitForLoadState('load'), a1.page.locator('form[name="reject"] button').first().click()]);
const mj = await findMail(`to:requester@e2e.local subject:rejected ${id2}`);
const tj = mj ? await mailText(mj) : '';
const smj = mj ? await mailShot(mj, 'A-15-3-mail-rejected') : null;
const fj = (tj.match(/https?:\/\/\S+/) || [])[0] ? await followAsRecipient(tj.match(/https?:\/\/\S+/)[0], 'requester') : null;
ev(`A-15 rejected mail:\n${tj}\n-> ${JSON.stringify(fj)}`);
const quoted = /> Link: http:\/\/evil/.test(t1) && !/^Link: http:\/\/evil/m.test(t1);
const exactlyOne = j2.nextBuildNumber - before === 1;
row('A-16', { roles: 'requester, approver-1, approver-2', V: `✓ decision form for designated approver-2 (and approver-1 while PENDING); after the decision approver-1 has ${forms} decision forms`, G: `${exactlyOne && /DATE.*2026-09-30/.test(JSON.stringify(params)) && /approver-2/.test(JSON.stringify(causes)) ? '✓' : '✗'} request to approver-1 + approver-2; approver-2 approved; exactly one build #${j2.lastBuild.number} ${j2.lastBuild.result} with DATE=2026-09-30, MODE=partial, cause "${(causes || []).map((c) => c.shortDescription).join('; ').slice(0, 110)}"; approver-1's view: "${(v1.match(/Status \w+/) || [''])[0]}", decided by approver-2`, R: 'n.a.', C: `${/approver-1;approver-2/.test(csv) && /,approver-2\s*$/.test(csv) && m1 && m2 ? '✓' : '✗'} requests.csv "approver-1;approver-2 ... ,approver-2" (decidedBy last); REQUEST_CREATED to both approvers`, E: [s1, s2, s3].every(Boolean) ? '✓ A-16-1..3' : '✗' });
row('A-15', { roles: 'requester, approver-1, approver-2 (as mail recipients)', V: 'n.a.', G: `${f1 && /Run Request/.test(f1.title) && fr && /Run Request/.test(fr.title) && fj && /Run Request/.test(fj.title) ? '✓' : '✗'} each link opened by its recipient while logged out lands on the login page and then on the request ("${f1 && f1.title}", "${fr && fr.title}", "${fj && fj.title}")`, R: 'n.a.', C: `${m1 && m2 && mr && mj && quoted ? '✓' : '✗'} REQUEST_CREATED to approver-1 and approver-2, APPROVED and REJECTED to requester; the reason line "Link: http://evil..." is quoted ("> Link:")`, E: sm && smr && smj ? '✓ A-15-1-mail-request-created, A-15-2-mail-approved, A-15-3-mail-rejected' : '✗', note: 'GRANT_EXPIRING in A-22/B15-06, pending EXPIRING observed separately (EXP-*)' });
await close();
