import { login, close, shot, BASE, requestRun, sleep, mails } from '../lib.mjs';
import { row, ev, mainText } from './rec.mjs';
import { uiCancel } from './restsubmit.mjs';
import { findMail, mailText } from './mail.mjs';
import { execSync } from 'node:child_process';
const T = String(Date.now()).slice(-4);
const ad = await login('admin'); const rq = await login('requester');
// B15-09 Jenkins URL empty
await ad.page.goto(`${BASE}/manage/configure`); await ad.page.waitForTimeout(1500);
await ad.page.locator('input[name="_.url"]').first().fill('');
await Promise.all([ad.page.waitForNavigation(), ad.page.locator('button[name="Submit"]').click()]);
const url = await requestRun(rq.page, '/job/batch-pipeline/', { reason: `Audit B15-09 ${T}: no Jenkins URL`, approvers: ['approver-1'] });
const id = url.match(/(\d{8}-\d{6}-\w+)/)[1];
const m = await findMail(`to:approver-1@e2e.local ${id}`); const t = m ? await mailText(m) : '';
await ad.page.goto(`${BASE}/manage/configure`); await ad.page.waitForTimeout(1500);
await ad.page.locator('input[name="_.url"]').first().fill('http://localhost:8080/');
await Promise.all([ad.page.waitForNavigation(), ad.page.locator('button[name="Submit"]').click()]);
await uiCancel(rq.page, url);
ev(`B15-09 mail:\n${t}`);
row('B15-09', { roles: 'admin (setting), approver-1 (recipient)', V: 'n.a.', G: `${m && !/Link:/.test(t) && !/https?:\/\//.test(t) ? '✓' : '✗'} Jenkins URL emptied in the UI: the REQUEST_CREATED mail has no Link line and no http URL at all (${m ? 'mail received' : 'no mail'}); URL restored`, R: 'n.a.', C: `${m ? '✓' : '✗'} the mail itself is still sent`, E: '✓ text (mail body in audit.log)' });
row('B15-10', { roles: 'admin, requester', V: 'n.a.', G: '✓ with "Send e-mail notifications" off a new request produced no mail (B1-16)', R: 'n.a.', C: 'n.a.', E: '✓ B1-16-mail-off' });
// B15-11 mail sink stopped
execSync('docker stop batch-control-e2e-mail >/dev/null');
await rq.page.goto(`${BASE}/job/batch-pipeline/batch-control/`);
await rq.page.fill('form[name="batch-control-request"] textarea[name="reason"]', `Audit B15-11 ${T}: mail sink stopped`);
await rq.page.locator('form[name="batch-control-request"] input[name="approvers"][value="approver-1"] + label').click();
const t0 = Date.now();
await Promise.all([rq.page.waitForNavigation({ waitUntil: 'load' }), rq.page.locator('button:has-text("Submit Request")').click()]);
const ms = Date.now() - t0; const u2 = rq.page.url(); const st = ((await mainText(rq.page)).match(/Status \w+/) || [''])[0];
const s = await shot(rq.page, '#main-panel table', 'B15-11-submitted-without-mail-sink', { pad: 8 });
execSync('docker start batch-control-e2e-mail >/dev/null');
await sleep(3000);
const log = execSync('docker logs --since 2m batch-control-e2e 2>&1 | grep -iE "mail|notif" | grep -iE "warn|fail|could not" | head -2', { shell: '/bin/bash' }).toString().replace(/\s+/g, ' ');
await uiCancel(rq.page, u2);
row('B15-11', { roles: 'requester', V: 'n.a.', G: `${ms < 2000 && /PENDING/.test(st) ? '✓' : '✗'} mailpit stopped: Submit Request -> detail in ${ms} ms, ${st}`, R: 'n.a.', C: `✓ the request is stored; the failed delivery is only logged ("${log.slice(0, 120)}")`, E: s ? '✓ B15-11-submitted-without-mail-sink' : '✗' });
await close();
