import { login, close, BASE, setGlobal } from '../lib.mjs';
import { ev } from './rec.mjs';
import { restSubmit } from './restsubmit.mjs';
const ad = await login('admin');
await setGlobal(ad.page, { approversText: '' });
const e = await restSubmit('requester', '/job/batch-pipeline/', { reason: 'audit B1-07 REST', approvers: ['approver-1'] });
await setGlobal(ad.page, { approversText: 'approver-1\napprover-2\napprover-disc\nadmin' });
await setGlobal(ad.page, { allowAdminSelfApproval: false });
const s = await restSubmit('admin', '/job/batch-pipeline/', { reason: 'audit B1-08 REST self off', approvers: ['admin'] });
await setGlobal(ad.page, { allowAdminSelfApproval: true });
const ok = await restSubmit('requester', '/job/batch-pipeline/', { reason: 'audit REST control (valid)', approvers: ['approver-1'] });
ev(`REST empty list ${JSON.stringify(e)}; self off ${JSON.stringify(s)}; control ${JSON.stringify(ok)}`);
await close();
