import { login, close, shot, job, BASE, requestRun, waitFor, sleep, api } from '../lib.mjs';
import { row, ev } from './rec.mjs';
import { activate, approveAs } from './helpers-e.mjs';
const J = 'batch-self';
await activate(J, 'Audit B5-21: self-triggering job, approved run');
const n = (await job(J, 'nextBuildNumber')).nextBuildNumber;
const rq = await login('requester');
const url = await requestRun(rq.page, `/job/${J}/`, { reason: `Audit B5-21 ${Date.now()}: approved run that triggers itself once`, approvers: ['approver-1'] });
await approveAs('approver-1', url);
await waitFor(async () => { const j = await job(J, 'nextBuildNumber,lastBuild[building]'); return j.nextBuildNumber >= n + 2 && !j.lastBuild.building; }, { timeout: 180000, every: 3000 });
await sleep(30000);
const bl = (await job(J, 'nextBuildNumber,builds[number,result,actions[causes[shortDescription]]]'));
const mine = bl.builds.filter((b) => b.number >= n).map((b) => `#${b.number} ${b.result} [${b.actions.flatMap((a) => (a.causes || []).map((c) => c.shortDescription)).join('; ')}]`);
await rq.page.goto(`${BASE}/job/${J}/${n + 1}/`);
const s = await shot(rq.page, rq.page.locator('#main-panel').locator('text=/Started by upstream/').first(), 'B5-21-child-started-by-upstream', { pad: 12 });
// hold again (HOLD flow)
await rq.page.goto(`${BASE}/job/${J}/`);
await rq.page.locator('.jenkins-alert a:has-text("request a hold")').click(); await rq.page.waitForLoadState('load');
await rq.page.fill('textarea[name="reason"]', 'Audit B5-21: back on hold'); await rq.page.locator('input[name="approvers"][value="approver-1"] + label').click();
await Promise.all([rq.page.waitForNavigation({ waitUntil: 'load' }), rq.page.locator('button:has-text("Submit Request")').click()]);
await approveAs('approver-1', rq.page.url(), 'hold');
ev(`B5-21 builds ${mine.join(' || ')}; next ${bl.nextBuildNumber}`);
row('B5-21', { roles: 'requester, approver-1', V: 'n.a.', G: `${bl.nextBuildNumber === n + 2 ? '✓' : '✗'} activated, approved run: exactly two builds ${mine.join(' || ')}, none after 30 s; back on hold afterwards`, R: 'n.a.', C: '✓ APPROVED_REQUEST and UPSTREAM rows (dashboard)', E: s ? '✓ B5-21-child-started-by-upstream' : '✗' });
await close();
