// Puts a job on hold through the real HOLD flow (requester -> approver-1). Usage: node hold.mjs <job>
import { login, close, BASE, shot } from '../lib.mjs';
import { ev, mainText } from './rec.mjs';
const J = process.argv[2];
const r = await login('requester'); const p = r.page;
await p.goto(`${BASE}/job/${J}/`);
await p.locator('.jenkins-alert a:has-text("request a hold")').click(); await p.waitForLoadState('load');
await p.fill('textarea[name="reason"]', `Audit: stop unattended runs of ${J} after the check`);
await p.locator('label:has-text("approver-1")').first().click();
await Promise.all([p.waitForLoadState('load'), p.click('button:has-text("Submit Request")')]);
const url = p.url();
const a = await login('approver-1');
await a.page.goto(url);
await a.page.fill('form[name="approve"] textarea[name="comment"]', 'ok');
await Promise.all([a.page.waitForLoadState('load'), a.page.locator('form[name="approve"] button').first().click()]);
ev(`HOLD ${J}: ${url} -> ${(await mainText(a.page)).slice(0, 160)}`);
await p.goto(`${BASE}/job/${J}/`);
ev(`HOLD ${J} notice: ${(await p.locator('.jenkins-alert:has-text("on hold")').first().innerText().catch(() => 'none')).replace(/\s+/g, ' ')}`);
if (process.argv[3]) await shot(p, p.locator('.jenkins-alert:has-text("on hold")').first(), process.argv[3]);
await close();
