import { login, close, BASE, api, requestGrant, decide, changeRows, sleep } from '../lib.mjs';
import { ev } from '../audit/rec.mjs';
import { formPost, uiRevoke } from '../audit/restsubmit.mjs';
const T = String(Date.now()).slice(-4); const gid = (u) => u.match(/(\d{8}-\d{6}-\w+)/)[1];
const { page } = await login('requester');
const g1 = await requestGrant(page, { type: 'JOB', scope: 'team/app-1', actions: ['CONFIGURE'], minutes: 15, reason: `C-15b ${T} configure only` }); await decide(g1.url);
const r1 = await formPost('requester', '/job/team/job/app-1/confirmRename', { newName: `ren-a-${T}` }); await sleep(800);
const a1 = (await api('admin', `/job/team/job/ren-a-${T}/api/json`)).status;
const ad = await login('admin');
const back = async (n) => { await ad.page.goto(`${BASE}/job/team/job/${n}/confirm-rename`); await ad.page.fill('input[name="newName"]', 'app-1'); await ad.page.waitForTimeout(600); await Promise.all([ad.page.waitForNavigation(), ad.page.locator('button[name="Submit"], button:has-text("Rename")').first().click()]); };
if (a1 === 200) await back(`ren-a-${T}`);
const g2 = await requestGrant(page, { type: 'FOLDER', scope: 'team', actions: ['CREATE'], pattern: 'app-ok', minutes: 15, reason: `C-15b ${T} create restricted` }); await decide(g2.url);
const r2 = await formPost('requester', '/job/team/job/app-1/confirmRename', { newName: `ren-b-${T}` }); await sleep(800);
const a2 = (await api('admin', `/job/team/job/ren-b-${T}/api/json`)).status; if (a2 === 200) await back(`ren-b-${T}`);
const viol = (await changeRows(/,GRANT_VIOLATION,team\/ren-/)).slice(0, 2);
await uiRevoke(gid(g1.url)); await uiRevoke(gid(g2.url));
ev(`C-15b configure-only rename -> ${r1.status} "${r1.msg.slice(0, 120)}" exists ${a1}; + restricted create -> ${r2.status} "${r2.msg.slice(0, 120)}" exists ${a2}; viol ${viol.join(' || ')}; app-1 ${(await api('admin', '/job/team/job/app-1/api/json')).status}`);
await close();
