import { login, close, BASE, api, requestGrant, decide, changeRows, sleep } from '../lib.mjs';
import { row, ev } from '../audit/rec.mjs';
import { formPost, uiRevoke } from '../audit/restsubmit.mjs';
const T = String(Date.now()).slice(-4); const gid = (u) => u.match(/(\d{8}-\d{6}-\w+)/)[1];
const { page } = await login('requester');
const g = await requestGrant(page, { type: 'FOLDER', scope: 'team', actions: ['CREATE', 'DELETE'], pattern: 'app-ok', minutes: 15, reason: `C-15 ${T} create+delete restricted` }); await decide(g.url);
const cfg = (await api('requester', '/job/team/job/app-1/configure')).status;
const v0 = (await changeRows(/,GRANT_VIOLATION,/)).length;
const r1 = await formPost('requester', `/job/team/job/app-1/confirmRename?newName=evil-${T}&name=app-1`, {});
const r2 = await formPost('requester', '/job/team/job/app-1/confirmRename', { newName: `evil2-${T}`, name: 'app-1' });
const r3 = await formPost('requester', '/job/team/job/app-1/confirmRename', { newName: 'app-ok' });
await sleep(1000);
const ex = await Promise.all([`evil-${T}`, `evil2-${T}`, 'app-ok', 'app-1'].map(async (n) => `${n}=${(await api('admin', `/job/team/job/${n}/api/json`)).status}`));
const nv = (await changeRows(/,GRANT_VIOLATION,/)).slice(0, (await changeRows(/,GRANT_VIOLATION,/)).length - v0);
const ad = await login('admin');
if (ex.includes('app-ok=200')) { await ad.page.goto(`${BASE}/job/team/job/app-ok/confirm-rename`); await ad.page.fill('input[name="newName"]', 'app-1'); await ad.page.waitForTimeout(600); await Promise.all([ad.page.waitForNavigation(), ad.page.locator('button[name="Submit"], button:has-text("Rename")').first().click()]); }
await uiRevoke(gid(g.url));
ev(`C-15 configure ${cfg}; ${JSON.stringify(r1)} | ${JSON.stringify(r2)} | matching ${JSON.stringify(r3)}; ${ex}; viol ${nv.map((l) => l.split(',').slice(6).join(',').slice(0, 100)).join(' || ')}; app-1 now ${(await api('admin', '/job/team/job/app-1/api/json')).status}`);
row('C-15', { roles: 'requester (FOLDER team CREATE+DELETE restricted to app-ok, no Configure on team/app-1)', V: 'n.a.', G: `${ex.includes(`evil-${T}=404`) && ex.includes(`evil2-${T}=404`) ? '✓' : '✗'} core\'s Create+Delete rename branch (confirmRename?newName=evil&name=app-1, and the form variant) refused: ${r1.status}, ${r2.status}; nothing renamed (${ex.slice(0, 2).join(', ')}); a matching name through the same branch -> ${r3.status}`, R: `${/app-ok|not allowed|restriction/.test(r1.msg + r2.msg) ? '✓' : '✗'} "${(r1.msg || r2.msg).slice(0, 150)}"`, C: `${nv.length >= 2 ? '✓' : '✗'} ${nv.length} GRANT_VIOLATION`, E: '✓ text', note: 'with a separate CONFIGURE window on the job, core renames it to any name (Configure is enough; the restriction governs only Create-authorised renames, SPEC 8 D-40a) - undocumented in LIMITATIONS 33 (DD-15)' });
await close();
