import { login, close, BASE, api, requestRun, sleep } from '../lib.mjs';
import { row, ev } from '../audit/rec.mjs';
import { formPost, uiCancel } from '../audit/restsubmit.mjs';
import { execSync } from 'node:child_process';
const { page } = await login('requester');
const url = await requestRun(page, '/job/batch-pipeline/', { reason: 'Verify C-21: approver ping-pong with the mail sink paused', approvers: ['approver-1'] });
const id = url.match(/(\d{8}-\d{6}-\w+)/)[1];
execSync('docker pause batch-control-e2e-mail');
const t0 = Date.now(); const codes = {}; const ui = [];
const loop = (async () => { for (let i = 0; i < 1100; i++) { const r = await formPost('requester', `/batch-control/requests/${id}/changeApprover`, { approvers: i % 2 ? 'approver-1' : 'approver-2' }); codes[r.status] = (codes[r.status] || 0) + 1; } })();
const a = await login('approver-2');
for (let k = 0; k < 5; k++) { const s = Date.now(); await a.page.goto(`${BASE}/batch-control/requests/`); ui.push(Date.now() - s); await sleep(1500); }
await loop; const dur = Date.now() - t0;
await sleep(5000);
const logs = execSync('docker logs --since 5m batch-control-e2e 2>&1 | grep -iE "notif|mail" | grep -iE "drop|queue|full|overflow|fail" | tail -3', { shell: '/bin/bash' }).toString().replace(/\s+/g, ' ');
execSync('docker unpause batch-control-e2e-mail');
const hist = (await api('admin', `/batch-control/requests/${id}/`)).text.match(/<tr>/g)?.length;
await uiCancel(page, url);
ev(`C-21 codes ${JSON.stringify(codes)} in ${dur} ms; UI loads ${ui}; logs "${logs}"; rows ${hist}`);
row('C-21', { roles: 'requester (script), approver-2 (UI)', V: 'n.a.', G: `${Math.max(...ui) < 2000 ? '✓' : '✗'} 1100 changeApprover calls (queue bound 1000) (${JSON.stringify(codes)}) in ${Math.round(dur / 1000)} s with mailpit paused; approver-2's Run Requests page loaded in ${ui.join(', ')} ms meanwhile`, R: 'n.a.', C: `${/drop|full|overflow/i.test(logs) ? '✓' : '✗'} log: "${logs.slice(0, 200) || 'no drop/overflow line'}"`, E: '✓ text',   note: 'SPEC D-36: the dispatch queue is bounded, overflow is dropped and logged' });
await close();
