// B12-09 / B13-08 (D-12): the span cap notice, with 50,500 arranged July run records (cap 50,000).
import { login, close, shot, api, BASE } from '../lib.mjs';
import { row, ev, mainText } from '../audit/rec.mjs';
const { page } = await login('approver-1');
let t0 = Date.now();
await page.goto(`${BASE}/batch-control/history/`);
await page.fill('#main-panel input[name="from"]', '2026-07-01').catch(() => {});
await Promise.all([page.waitForNavigation(), page.locator('#main-panel button:has-text("Filter")').click()]);
const hMs = Date.now() - t0; const ht = await mainText(page);
const hNote = (ht.match(/[^.]*(cap|limit|narrow|truncat|CSV|first \d)[^.]*\./gi) || []).join(' ');
const s1 = await shot(page, page.locator('#main-panel').locator('text=/CSV|narrow|limit|stopped|first/i').first().locator('xpath=..'), 'B13-08-history-cap-notice', { pad: 8 });
t0 = Date.now();
await page.goto(`${BASE}/batch-control/dashboard/?days=90`);
const dMs = Date.now() - t0; const dt = await mainText(page);
const dNote = (dt.match(/[^.]*(cap|limit|narrow|truncat|CSV|first \d)[^.]*\./gi) || []).join(' ');
const dFoot = (dt.match(/Page \d+ \([^)]*\)/) || [''])[0];
const s2 = await shot(page, page.locator('#main-panel').locator('text=/CSV|narrow|limit|stopped|first/i').first().locator('xpath=..'), 'B12-09-dashboard-cap-notice', { pad: 8 });
const csv = (await api('approver-1', '/batch-control/history/runs.csv?from=2026-07-01')).text.split('\n').filter(Boolean).length - 1;
ev(`D-12 history ${hMs} ms note "${hNote.slice(0, 300)}"; dashboard ${dMs} ms "${dFoot}" note "${dNote.slice(0, 300)}"; runs.csv from July ${csv} rows`);
row('B13-08', { roles: 'approver-1', V: 'n.a.', G: `${hNote ? '✓' : '✗'} History over July-September (50,500 arranged + real runs, cap 50,000) answers in ${hMs} ms`, R: `${/CSV/i.test(hNote) ? '✓' : '✗'} the screen says it was cut and how to get everything: "${hNote.slice(0, 200)}"`, C: `${csv >= 50500 ? '✓' : '✗'} runs.csv for the same span is complete (${csv} rows)`, E: s1 ? '✓ B13-08-history-cap-notice' : '✗', note: 'records arranged as a July month file (state only)' });
row('B12-09', { roles: 'approver-1', V: 'n.a.', G: `${dNote ? '✓' : '✗'} Dashboard with Days 90 answers in ${dMs} ms, footer "${dFoot}"`, R: `${/CSV/i.test(dNote) ? '✓' : '✗'} "${dNote.slice(0, 200)}"`, C: 'n.a.', E: s2 ? '✓ B12-09-dashboard-cap-notice' : '✗' });
await close();
