// DEF-37 / C-08 with a global default build authorization (auditor, no Configure): no warning, and the self-grant fails.
import { login, close, shot, api, job, BASE, decide, changeRows, sleep, waitFor, clickBuildEntry } from '../lib.mjs';
import { ev, mainText } from '../audit/rec.mjs';
import { uiRevoke } from '../audit/restsubmit.mjs';
import fs from 'node:fs';
const J = 'batch-upstream';
const gUrl = fs.readFileSync('../out/final-c08.url', 'utf8').trim();
const a = await login('approver-1'); await a.page.goto(gUrl);
const warnAfter = /run as SYSTEM|account with Configure/i.test(await mainText(a.page));
await shot(a.page, a.page.locator('#main-panel table').first(), 'C-08-5-request-without-warning', { pad: 8 });
await a.context.close();
await decide(gUrl, 'approve', 'ok');
const orig = (await api('admin', `/job/${J}/config.xml`, { raw: true })).text;
const x = orig.replace(/<script>[\s\S]*?<\/script>/, `<script>properties([authorizationMatrix(inheritanceStrategy: inheritingGlobal(), entries: [user(name: 'requester', permissions: ['Job/Configure', 'Job/Read'])])])\necho 'c08-final'</script>`);
const put = await api('requester', `/job/${J}/config.xml`, { method: 'POST', body: x, headers: { 'Content-Type': 'application/xml' } });
const n = (await job(J, 'nextBuildNumber')).nextBuildNumber;
const rq = await login('requester'); await rq.page.goto(`${BASE}/job/${J}/`);
await clickBuildEntry(rq.page, 'Build Now');
await waitFor(async () => { const j = await job(J, 'lastBuild[number,building]'); return j.lastBuild && j.lastBuild.number >= n && !j.lastBuild.building; }, { timeout: 120000 });
await sleep(3000);
const res = (await job(J, 'lastBuild[number,result]')).lastBuild;
const con = (await api('admin', `/job/${J}/${res.number}/consoleText`, { raw: true })).text.split('\n').filter((l) => /Running as|c08|ERROR|missing|Finished|permission/i.test(l)).slice(0, 6).join(' | ');
const entries = ((await api('admin', `/job/${J}/config.xml`, { raw: true })).text.match(/requester/g) || []).length;
await uiRevoke(gUrl.match(/(\d{8}-\d{6}-\w+)/)[1]);
const after = (await api('requester', `/job/${J}/configure`)).status;
await api('admin', `/job/${J}/config.xml`, { method: 'POST', body: orig, headers: { 'Content-Type': 'application/xml' } });
await rq.page.goto(`${BASE}/job/${J}/${res.number}/console`);
await shot(rq.page, '#main-panel pre, #out, .console-output', 'C-08-6-build-as-auditor', { pad: 8 });
fs.writeFileSync('../out/final-c08.json', JSON.stringify({ warnAfter, put: put.status, n: res.number, result: res.result, con, entries, after }));
ev(`F4c warning on request after default ${warnAfter}; put ${put.status}; #${res.number} ${res.result} "${con}"; requester entries ${entries}; configure after revoke ${after}`);
await close();
