import { login, close, BASE, groovy, shot, api } from '../lib.mjs';
import { row, ev } from '../audit/rec.mjs';
const ROLES = `import com.synopsys.arc.jenkins.plugins.rolestrategy.RoleType; def s = jenkins.model.Jenkins.get().authorizationStrategy; println s.class.simpleName + ' ' + RoleType.values().collect { t -> t.toString() + ':' + s.getRoleMap(t).getGrantedRolesEntries().collect { k, v -> k.name + '=' + v.collect { it.sid } } }.join(' ')`;
const { page } = await login('admin');
const b0 = await api('approver-2', '/batch-control/requests/'); 
await page.goto(`${BASE}/manage/role-strategy/`); await page.waitForTimeout(2500);
const glob = page.locator('#main-panel').locator('h2:has-text("Global roles"), h3:has-text("Global roles")').first().locator('xpath=following::*[.//button[normalize-space()="Add User"]][1]');
await page.locator('button:has-text("Add User")').first().click(); await page.waitForTimeout(800);
const dlgText = (await page.locator('dialog[open]').innerText().catch(() => 'no dialog')).replace(/\s+/g, ' ');
await page.locator('dialog[open] input').first().fill('approver-2'); await page.waitForTimeout(800);
const inline = (await page.locator('dialog[open]').innerText().catch(() => '')).replace(/\s+/g, ' ');
await page.locator('dialog[open] button[data-id="ok"], dialog[open] button:has-text("Add")').first().click(); await page.waitForTimeout(1000);
const r = page.locator('tr', { hasText: /E2E Approver Two|approver-2/ }).first();
const cells = await r.locator('input[type="checkbox"]').count();
// columns: admin, bc-approver, bc-requester
await r.locator('input[type="checkbox"]').nth(1).locator('xpath=following-sibling::label[1] | ..').first().click().catch(async () => r.locator('input[type="checkbox"]').nth(1).check({ force: true }));
const s1 = await shot(page, page.locator('table').first(), 'B8-R1-1-assign-approver-2', { pad: 8 });
await Promise.all([page.waitForNavigation().catch(() => null), page.locator('button:has-text("Save")').click()]);
const after = await groovy(ROLES);
const b1 = await api('approver-2', '/batch-control/requests/');
await page.goto(`${BASE}/manage/role-strategy/`); await page.waitForTimeout(2000);
const s2 = await shot(page, page.locator('table').first(), 'B8-R1-2-after-save', { pad: 8 });
ev(`R1 dialog "${dlgText.slice(0, 200)}" inline "${inline.slice(0, 200)}" cells ${cells}; roles ${after}; approver-2 requests ${b0.status}->${b1.status}`);
const ok = /bc-approver=\[approver-1, approver-2\]|bc-approver=\[approver-2, approver-1\]/.test(after);
row('B8-R1', { roles: 'admin (role pages), approver-2 (effect)', V: '✓ Role Management shows every assigned user by name (E2E Administrator, E2E Approver One, E2E Requester) - no 404 page in the rows (DEF-20 fixed)', G: `${ok ? '✓' : '✗'} Add User approver-2, tick bc-approver, Save -> ${after.split(' ').slice(1, 2).join(' ')}; approver-2 keeps Run Requests access (${b1.status})`, R: 'n.a.', C: 'n.a.', E: s1 && s2 ? '✓ B8-R1-role-management, B8-R1-1..2' : '✗', note: 'role-strategy 918 puts the assignments on Role Management; the old assign-roles URL answers 404 (core page, not ours)' });
await close();
