import { login, close, BASE, shot, log } from './lib.mjs';
const L = 'section-a.log';
const { page } = await login('admin');
await page.goto(BASE + '/manage/');
const m1 = page.locator('.jenkins-alert:has-text("no build authenticator")').first();
const m2 = page.locator('.jenkins-alert:has-text("direct Item Create")').first();
await shot(page, [m1, m2], 'A-04-manage', { pad: 10 });
const btn = m2.locator('a, button').filter({ hasText: 'Review authorization strategy' }).first();
log(L, `A-04 standing-permission monitor text names configurer: ${(await m2.innerText()).includes('configurer')}`);
const [nav] = await Promise.all([page.waitForNavigation({ waitUntil: 'load' }).catch(() => null), btn.click()]);
log(L, `A-04 "Review authorization strategy" -> ${page.url()} ${nav && nav.status()}`);
// header popup
await page.goto(BASE + '/');
const bell = page.locator('#visible-am-button, #visible-sec-am-button, a[href$="/manage/"] .am-monitor__count, .jenkins-header a[href="/manage"]').first();
await page.locator('a[href="/manage"], #root-action-ManageJenkinsAction').first().hover().catch(() => {});
await page.waitForTimeout(1500);
const pop = page.locator('.tippy-box, .am-list').first();
log(L, `A-04 header popup visible: ${await pop.isVisible().catch(() => false)} text: ${(await pop.innerText().catch(() => '')).replace(/\s+/g, ' ').slice(0, 300)}`);
if (await pop.isVisible().catch(() => false)) await shot(page, pop, 'A-04-popup', { pad: 10 });
// dismiss the SYSTEM-builds monitor
await page.goto(BASE + '/manage/');
const m1b = page.locator('.jenkins-alert:has-text("no build authenticator")').first();
await m1b.locator('button').last().click();
await page.waitForTimeout(1500);
await page.goto(BASE + '/manage/');
log(L, `A-04 after Dismiss, SYSTEM-builds monitor still shown: ${await page.locator('.jenkins-alert:has-text("no build authenticator")').count()}`);
await page.goto(BASE + '/manage/configureSecurity/');
const am = page.getByText('Batch Control', { exact: false }).filter({ hasNot: page.locator('select') });
const monList = await page.locator('.jenkins-checkbox:has-text("Batch Control"), label:has-text("Batch Control")').allInnerTexts();
log(L, `A-04 security page monitor toggles: ${JSON.stringify(monList)}`);
const first = page.locator('label:has-text("Batch Control")').first();
if (await first.count()) await shot(page, page.locator('label:has-text("Batch Control")'), 'A-04-monitor-toggles', { pad: 10 });
await close();
