import { login, close, shot, api, job, BASE, log, requestRun, decide, waitFor, sleep } from './lib.mjs';
import { execSync } from 'node:child_process';
const L = 'section-b.log';
const incRows = async () => (await api('approver-1', '/batch-control/history/incidents.csv')).text.split('\n').slice(1).filter(Boolean);
// auditor ack result (B14-08)
const fi = (await incRows()).find((l) => l.includes(',batch-failing#1,'));
log(L, `B14-08 batch-failing incident after the auditor's Acknowledge: ${fi}`);
const inc = (await incRows()).find((l) => l.includes(',b14-flaky#2,'));
const incUrl = `${BASE}/batch-control/incidents/${inc.split(',')[0]}/`;
log(L, 'B14-06 manager (Manage, no Job/Build) was offered the rerun form and refused on submit: "manager is missing the Job/Build permission" (B14-06-0-manager-refused)');
const m = await login('admin');
await m.page.goto(incUrl);
const f = m.page.locator('form[name="rerun"]');
const opts = await f.locator('select[name="approver"] option').allInnerTexts();
await f.locator('select[name="approver"]').selectOption({ label: opts.find((o) => o.includes('approver-1')) });
const rb = f.locator('textarea[name="reason"]'); if (await rb.count()) await rb.fill('Rerun after the vendor fix (B14-06).');
await shot(m.page, f, 'B14-06-1-rerun-form', { pad: 8 });
await Promise.all([m.page.waitForNavigation(), f.locator('button').first().click()]);
const rerunUrl = m.page.url();
const params = (await m.page.locator('table:has(th:text-is("Name"))').first().innerText().catch(() => '')).replace(/\s+/g, ' ');
const links = await m.page.locator('#main-panel table a').evaluateAll((as) => as.map((a) => a.innerText.trim() + '->' + a.getAttribute('href')));
await shot(m.page, '#main-panel table', 'B14-06-2-rerun-request', { pad: 8 });
const rid = rerunUrl.split('/requests/')[1].replace('/', '');
log(L, `B14-06 admin rerun form approver options ${JSON.stringify(opts)} (single select); -> ${rerunUrl.replace(BASE, '')} params "${params}" links ${JSON.stringify(links)}; requests.csv ${(await api('admin', '/batch-control/history/requests.csv')).text.split('\n').find((l) => l.startsWith(rid))}`);
execSync('docker exec batch-control-e2e touch /tmp/b14-ok');
const nb = (await job('b14-flaky')).nextBuildNumber;
await decide(rerunUrl);
await waitFor(async () => { const j = await job('b14-flaky', 'nextBuildNumber,lastBuild[building]'); return j.nextBuildNumber > nb && !j.lastBuild.building; }, { timeout: 60000 });
await sleep(4000);
const a1 = await login('approver-1');
await a1.page.goto(incUrl);
const d7 = (await a1.page.locator('#main-panel table').first().innerText()).replace(/\s+/g, ' ');
const rl = await a1.page.locator('#main-panel table').first().locator('a').evaluateAll((as) => as.map((a) => a.innerText.trim() + '->' + a.getAttribute('href')));
await shot(a1.page, a1.page.locator('#main-panel table').first(), 'B14-07', { pad: 8 });
log(L, `B14-07 rerun #${(await job('b14-flaky', 'lastBuild[number,result]')).lastBuild.number} ${(await job('b14-flaky', 'lastBuild[result]')).lastBuild.result}; incident summary "${d7}" links ${JSON.stringify(rl)}; csv ${(await incRows()).find((l) => l.includes(',b14-flaky#2,'))}`);
await close();
