import { login, close, shot, BASE, log, api, requestRun, decide, groovy, sleep, changeRows } from './lib.mjs';
import { execSync } from 'node:child_process';
const L = 'section-b.log';
log(L, `B18-02/03 JVM: ${(await groovy('println java.util.Locale.getDefault().toString() + " " + java.util.TimeZone.getDefault().getID() + " digits=" + String.format("%d", 2026)')).trim()}`);
const rq = await login('requester');
const url = await requestRun(rq.page, '/job/batch-pipeline/', { reason: 'Created under th_TH_TH and UTC (B18-02/03).', approvers: ['approver-1'] });
await decide(url);
await sleep(12000);
const id = url.split('/requests/')[1].replace('/', '');
const files = execSync(`docker exec batch-control-e2e sh -c 'cd /var/jenkins_home/batch-control && ls runs changes requests/run | tail -4; ls requests/run | grep ${id}'`).toString().replace(/\n/g, ' ');
const nonAscii = execSync(`docker exec batch-control-e2e sh -c 'find /var/jenkins_home/batch-control -newer /var/jenkins_home/config.xml | LC_ALL=C grep -P "[^\\x00-\\x7F]" | head -3; echo end'`).toString().trim();
log(L, `B18-02 new request id ${id} ASCII ${/^[\x00-\x7F]+$/.test(id)}; store files: ${files}; non-ASCII new paths: ${nonAscii}`);
const a1 = await login('approver-1');
await a1.page.goto(url);
const screen = (await a1.page.locator('#main-panel table').first().innerText()).replace(/\s+/g, ' ');
await shot(a1.page, a1.page.locator('#main-panel table').first(), 'B18-03-1-request-utc', { pad: 8 });
const row = (await api('admin', '/batch-control/history/requests.csv')).text.split('\n').find((l) => l.startsWith(id));
await a1.page.goto(`${BASE}/batch-control/history/`);
const hist = (await a1.page.locator('#main-panel').innerText()).replace(/\s+/g, ' ');
const from = await a1.page.inputValue('#main-panel input[name="from"]').catch(() => '?');
await shot(a1.page, ['#main-panel form', a1.page.locator('#main-panel table tbody tr').first()], 'B18-03-2-history-utc', { pad: 8 });
await a1.page.goto(`${BASE}/batch-control/changes/`);
const month = (await a1.page.locator('#main-panel input[name="month"]').inputValue().catch(() => '?'));
log(L, `B18-03 screen dates "${(screen.match(/Created [^A-Z]+ ?[A-Z]{2,4}/) || [''])[0]}" vs requests.csv createdAt ${row && row.split(',')[7]}; history from=${from}, first row "${(hist.match(/#\d+ \S+ \S+ .{0,60}/) || [''])[0]}"; changes month input ${month}; summary ${(hist.match(/Monthly Summary \([^)]*\)/) || [''])[0]}`);
// retention still works under the locale
const ad = await login('admin');
await ad.page.goto(`${BASE}/batch-control/changes/?month=2026-09`);
log(L, `B18-02 Change Records ?month=2026-09 -> rows ${await ad.page.locator('#main-panel table tbody tr').count()}; retention run: ${(await groovy('io.jenkins.plugins.batchcontrol.ops.RetentionPeriodicWork.all().get(io.jenkins.plugins.batchcontrol.ops.RetentionPeriodicWork).doRun(); println "ok"')).split('\n')[0]}; month files after: ${execSync("docker exec batch-control-e2e sh -c 'ls /var/jenkins_home/batch-control/runs /var/jenkins_home/batch-control/changes'").toString().replace(/\n/g, ' ')}`);
await close();
