import { login, close, shot, api, BASE, requestGrant, decide, sleep, groovy } from '../lib.mjs';
import { row, ev } from './rec.mjs';
import { uiRevoke } from './restsubmit.mjs';
const m = await login('manager'); await m.page.goto(`${BASE}/batch-control/grants/`);
const act = (await m.page.locator('table:has(th:has-text("Expires")) tbody tr').allInnerTexts()).map((t) => t.replace(/\s+/g, ' '));
ev(`active grants: ${JSON.stringify(act)}`);
for (const a of act) { const id = (a.match(/^(\d{8}-\d{6}-\w+)/) || [])[1]; if (id) ev(`revoke ${id}: ${await uiRevoke(id)}`); }
const rq = await login('requester'); const p = rq.page;
const T = String(Date.now()).slice(-4);
const g = await requestGrant(p, { type: 'FOLDER', scope: 'team', actions: ['CREATE'], minutes: 15, reason: `Audit B9-04 ${T}: create under the guard (15 min)` });
await decide(g.url);
const nm = `app-c35-${T}`;
await p.goto(`${BASE}/job/team/newJob`); await p.fill('#name', nm); await p.locator('label:has-text("Freestyle project")').first().click();
const [r0] = await Promise.all([p.waitForNavigation(), p.locator('#ok-button').click()]);
const landed = p.url(); const st0 = r0.status();
await Promise.all([p.waitForNavigation(), p.locator('button[name="Submit"]').click()]);
const c1 = (await p.goto(`${BASE}/job/team/job/${nm}/configure`)).status();
const s = await shot(p, '#main-panel, body', 'B9-04-configure-own-created-item', { pad: 8 });
const c2 = (await p.goto(`${BASE}/job/team/job/app-1/configure`)).status();
const entries = ((await api('admin', `/job/team/job/${nm}/config.xml`, { raw: true })).text.match(/<permission>[^<]+<\/permission>/g) || []);
const acl = await groovy(`def j = jenkins.model.Jenkins.get().getItemByFullName('team/${nm}'); def u = hudson.model.User.getById('requester', false).impersonate2(); println 'hasConfigure=' + j.getACL().hasPermission2(u, hudson.model.Item.CONFIGURE)`);
ev(`B9-04b created ${nm}: after OK ${st0} ${landed}; configure ${c1}; app-1 ${c2}; entries ${entries}; ${acl}`);
await uiRevoke(g.url.match(/(\d{8}-\d{6}-\w+)/)[1]);
row('B9-04', { roles: 'requester (CREATE window on team/)', V: 'n.a.', G: `${entries.length === 0 && c1 === 200 && c2 === 403 ? '✓' : '✗'} team/${nm} created under only a 15-min CREATE window: no permission entry on the item (${entries.length}); right after OK the new job's configure page ${st0 === 200 && /configure/.test(landed) ? 'opened (200)' : st0}; reopening it later -> ${c1} (${acl}); team/app-1 -> ${c2}`, R: `${c1 === 200 ? 'n.a.' : '✗ the creator is locked out of the job he just created during his window: core 403 (D-35c promises Configure on it while the window lasts)'}`, C: 'n.a.', E: s ? '✓ B9-04-configure-own-created-item' : '✗', defect: c1 === 200 ? '' : 'DEF-36 (new)' });
await close();
