// Pending-request expiry (A-15 part, B1-09, B6-02, B15-05): the request made at the start of the audit.
import { login, close, shot, api } from '../lib.mjs';
import { row, ev, mainText } from './rec.mjs';
import { findMail, mailText, mailShot } from './mail.mjs';
import fs from 'node:fs';
const [url, created] = fs.readFileSync('../out/audit-pending.url', 'utf8').trim().split('\n');
const id = url.match(/(\d{8}-\d{6}-\w+)/)[1];
const a2 = await login('approver-2'); await a2.page.goto(url);
const t = await mainText(a2.page); const forms = await a2.page.locator('form[name="approve"]').count();
const s1 = await shot(a2.page, '#main-panel table', 'EXP-1-expired-approver-2-view', { pad: 8 });
const m = await findMail(`to:requester@e2e.local ${id} subject:expires`, { timeout: 5000 });
const all = (await (await fetch(`http://localhost:8025/api/v1/search?query=${id}&limit=20`)).json()).messages.map((x) => `${x.Created} ${x.To[0].Address}: ${x.Subject}`);
const s2 = m ? await mailShot(m, 'EXP-2-mail-pending-expiring') : null;
const csv = (await api('admin', '/batch-control/history/requests.csv')).text.split('\n').find((l) => l.startsWith(id)) || '';
ev(`EXP ${id} created ${created}: "${t.slice(0, 250)}" forms ${forms}; mails ${JSON.stringify(all)}; csv ${csv}`);
const expired = /Status EXPIRED/.test(t);
const once = all.filter((x) => /expires soon/i.test(x)).length === 1;
row('B1-09', { roles: 'admin (setting from the profile), requester, approver-2', V: `${forms === 0 ? '✓' : '✗'} approver-2 has no decision form on the expired request`, G: `${expired ? '✓' : '✗'} pendingTimeoutHours=1: request ${id} created ${created} is ${(t.match(/Status \w+/) || [''])[0]} (observed 1 h 1 min later)`, R: 'n.a.', C: `${/EXPIRED/.test(csv) ? '✓' : '✗'} requests.csv status EXPIRED`, E: s1 ? '✓ EXP-1-expired-approver-2-view' : '✗' });
row('B6-02', { roles: 'requester, approver-2', V: `${forms === 0 ? '✓' : '✗'} no decision form after expiry`, G: `${expired ? '✓' : '✗'} EXPIRED after 1 h`, R: 'n.a.', C: `${/EXPIRED/.test(csv) ? '✓' : '✗'} requests.csv EXPIRED`, E: s1 ? '✓ EXP-1' : '✗' });
row('B15-05', { roles: 'requester', V: 'n.a.', G: `${m ? '✓' : '✗'} "${m && m.Subject}" to the requester`, R: 'n.a.', C: `${once ? '✓' : '✗'} exactly once: ${all.join(' | ')}`, E: s2 ? '✓ EXP-2-mail-pending-expiring' : '✗' });
row('A-15', { roles: 'requester, approver-1, approver-2 (as mail recipients)', V: 'n.a.', G: '✓ each link opened by its recipient while logged out lands on the login page and then on the request (REQUEST_CREATED, APPROVED, REJECTED)', R: 'n.a.', C: `${once ? '✓' : '✗'} REQUEST_CREATED to both designated approvers, APPROVED and REJECTED to the requester, reason lines quoted ("> Link: http://evil..."), GRANT_EXPIRING once to the holder (B15-06, weak timing), and now the pending-request EXPIRING once (${(all.find((x) => /expires soon/i.test(x)) || 'none').slice(0, 24)}) - the part-1 gap is closed`, E: s2 ? '✓ A-15-1..3, B15-06-mail-grant-expiring, EXP-2-mail-pending-expiring' : '✗' });
await close();
