import { login, close, BASE, log, job, sleep, shot } from './lib.mjs';
const L = 'section-b.log';
const n0 = (await job('batch-self')).nextBuildNumber;
const rq = await login('requester');
await rq.page.goto(`${BASE}/job/batch-self/`);
await rq.page.locator('#main-panel a:has-text("request a hold")').click(); await rq.page.waitForLoadState('load');
await rq.page.fill('textarea[name="reason"]', 'batch-self re-triggers itself in a loop; stop unattended runs (HOLD).');
await rq.page.locator('input[name="approvers"][value="approver-1"] + label').click();
await Promise.all([rq.page.waitForNavigation(), rq.page.locator('button:has-text("Submit Request")').click()]);
const url = rq.page.url();
const ap = await login('approver-1');
await ap.page.goto(`${BASE}/batch-control/`);
const inbox = (await ap.page.locator('#main-panel .jenkins-alert').allInnerTexts()).join(' ').replace(/\s+/g, ' ');
await ap.page.goto(url); await ap.page.fill('form[name="approve"] textarea[name="comment"]', 'stop it');
await shot(ap.page, '#main-panel', 'D-10-hold-decision', { pad: 6 });
await Promise.all([ap.page.waitForLoadState('load'), ap.page.locator('form[name="approve"] button').first().click()]);
const n1 = (await job('batch-self')).nextBuildNumber;
await sleep(20000);
const n2 = (await job('batch-self')).nextBuildNumber;
await rq.page.goto(`${BASE}/job/batch-self/`);
const notice = (await rq.page.locator('#main-panel .jenkins-alert').allInnerTexts()).map((t) => t.replace(/\s+/g, ' ').slice(0, 100));
log(L, `HOLD of looping batch-self: builds ${n0} before the request, ${n1} at approval, ${n2} 20 s later; approver landing "${inbox}"; job notice ${JSON.stringify(notice)}`);
await close();
