import { login, close, BASE, shot } from './lib.mjs';
const [u, path, label, name] = process.argv.slice(2);
const { page } = await login(u);
await page.goto(BASE + path);
const entry = page.locator('#side-panel a').filter({ hasText: label }).first();
await entry.click();
await page.waitForTimeout(1500);
const toast = page.locator('#notification-bar, .jenkins-notification').first();
console.log('toast:', (await toast.innerText().catch(() => '')).replace(/\s+/g, ' '), 'url', page.url());
await shot(page, [entry, toast], name, { pad: 12 });
await close();
